RepConvLangArray.da = {
	AUTHOR:'pcgeni, Bologna, Hypatia, RAC2720, Beentherebefore, Jiluske, life2',
	BTNCONV:'Konventere',
	BTNGENER:'Generere',
	BTNVIEW:'Smugkig',
	BTNSAVE:'Gem',
	MSGTITLE:'Konvertér report',
	MSGQUEST:'Hvilke data ønsker du at offentliggøre?',
	MSGBBCODE:'Ved offentliggørelse af rapporten, kan du sætte bruge den i nyheder og forums ved at bruge BBCode.',
	MSGRESOURCE:'Plyndring',
	MSGUNITS:'Enheder',
	MSGBUILD:'Bygninger',
	MSGUSC:'Brugte sølvmønter',
	MSGRAW:'Rå materialer',
	SUPPORT:'Hjælp',
	SPY:'Spionere',
	CONQUER:'Overvundet',
	LOSSES:'Tab',
	HIDDEN:'Skjulte',
	NOTUNIT:'[i]Ingen[/i]',
	TOWN:'[i]By:[/i] ',
	PLAYER:'[i]Spiller:[/i] ',
	ALLY:'[i]Alliance:[/i] ',
	CAST:'udgiver:',
	ONTOWER:'På byen:',
	MSGHIDAD:'Skjul byer',
	MSGFORUM:'Rapporten vil offentliggøres',
	BBALLY:'alliance forums / i beskeden',
	BBFORUM:'Eksternt forum',
	ICOCLOSE:'Luk',
	ICOHELP:'Om konverteren',
	MSGPREVIEW:'<b>Report overblik</b>',
	HELPTAB1:'Omkring',
	HELPTAB2:'Hvordan virker det',
	HELPTAB3:'Ændringer',
	HELPTAB4:'Indstillinger',
	MSGHUMAN:{
		OK:'Informationerne er gemt',
		ERROR:'En fejl opstod under skrivning',
	},
	LABELS:{
		attack:{
			ATTACKER:'Angriber',
			DEFENDER:'Forsvarer',
			MSGHIDAT:'angriber',
			MSGHIDDE:'forsvarer',
			MSGATTUNIT:'Angribende hær',
			MSGDEFUNIT:'Forsvarende hær',
		},
		support:{
			ATTACKER:'Hjælper',
			DEFENDER:'Hjulpet',
			MSGHIDAT:'hjælper',
			MSGHIDDE:'hjulpet',
			MSGATTUNIT:'Støttehær',
			MSGDEFUNIT:'Forsvarende hær',
		},
		espionage:{
			ATTACKER:'Spionere',
			DEFENDER:'Spioneret',
			MSGHIDAT:'spionere',
			MSGHIDDE:'udspioneret',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'kommando detaljer',
	MSGRETURN:'(tilbage)',
	MSGGENBBCODE:'Generere en liste af BBCode',
	MSGDEFSITE:'Besejret...',
	MSGLOSSITE:'Tab...',
	MSGASATT:'...som angriber',
	MSGASDEF:'...som forsvarer',
	MSGDIFF1:'vis ikke forskelle',
	MSGDIFF2:'vis forskelle',
	MSGDIFF3:'vis kun forskellene',
	BBCODELIMIT:'Grundet den begrænsede tekstmængde i en boks, og for at undgå en lang liste, er datasne inddelt i hver deres boks.',
	CHKPOWERNAME:'Vis den tilbageværende tid indtil magien kan bruges',
	CHKFORUMTABS:'Overskriv scrolls fanerne på forummet for multi line',
	STATSLINK:'Statistikker fra fremviseren',
	BTNSUPPLAYERS:'Liste over spillere',
	CHKUNITSCOST:'Rapporten viser tabene af tabte enheder',
	CHKOCEANNUMBER:'Vis havnumre',
	MSGRTLBL:'Oprør information',
	MSGRTSHOW:'tilføj igangværende oprør information',
	MSGRTONLINE:'Er du online når det røde oprør er i gang?',
	MSGRTYES:'Ja',
	MSGRTNO:'Nej',
	MSGRTGOD:'Gud',
	MSGRTCSTIME:'KS tid',
	MSGRTONL:'til stede?',
	MSGRTERR:'Du er i den forkerte by!<br/>For at lave den rigtige oprørs information, gå til byen: ',
	BBTEXT:'tekst version',
	BBHTML:'tabel version',
	MSG413ERR:'<h3>Den generede rapport er for stor.</h3><p>Brug andre muligeheder for at rapportere uden problemer</p>',
	CHKREPORTFORMAT:'Generer rapport ved brug af tabbeler',
	WALLNOTSAVED:'Muren er ikke gemt',
	WALLSAVED:'Muren er gemt',
	POPSELRECRUNIT:'klik, for at vælge standard produktions enhed',
	POPRECRUNITTRADE:'klik, for at indsætte de nødvendige ressourcer for den valgte enhed',
	POPINSERTLASTREPORT:'Indsæt den senest konventerede rapport',
	MSGCOPYREPORT:'Rapporten er gemt. Vær sød at klikke [paste_icon] på forummet eller under ny besked for at indsætte den',
	POPDISABLEALARM:'Slå alarm fra',
	SOUNDSETTINGS:'Lyd indstillinger',
	CHKSOUNDMUTE:'Lydløs',
	SOUNDVOLUME:'Lydstyke',
	SOUNDURL:'Lyd fil url',
	CHKSOUNDLOOP:'spring',
	POPSOUNDLOOP:'Spring i numrene',
	POPSOUNDMUTE:'Slå lyden fra',
	POPSOUNDPLAY:'Spil med nuværende indstillinger',
	POPSOUNDSTOP:'Stop afspilning',
	POPSOUNDURL:'Url sti til lydfilen',
	STATS:{
		PLAYER:'Spiller statistik',
		ALLY:'Alliance statistik',
		TOWN:'By statistik',
		CHKINACTIVE:'Vis inaktive spillere',
		INACTIVE:'Inaktive',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'GRCRTools Hær Bygnings Hjælper',
			UNITFRAME:'vælg din enhed',
			DESCRIPTION1:'I denne by, har du [population] fri befolkning',
			DESCRIPTION2:'Hvilket er nok til at rekruttere [max_units]',
			DESCRIPTION3:'Du [yesno] har udforsket  [research].',
			DESCRIPTION4:'Du kan maximalt sætte [max_queue] enheder igang   ',
			TARGET:'vælg dit byggemål',
			PACKAGE:'ressourcer per bestilling (enhed)',
			BTNSAVE:'gem indstillingerne',
			TOOLTIPOK:'klik, for at vælge enhed du vil sende resourser til',
			TOOLTIPNOTOK:'enheder er ikke udforsket',
			HASRESEARCH:'GØR',
			NORESEARCH:'GØR IKKE',
			SETTINGSAVED:'Opsætningen for [by] er gemt',
		},
		RESWND:{
			RESLEFT:'tilgængelige ressourcer',
			IMGTOOLTIP:'klik, for at indsætte ressourcer',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Ny version tilgængelig',
		INSTALL:'Installer',
		REMINDER:'Påmind mig senere',
		REQRELOAD:'Kræver genindlæsning af siden',
		RELOAD:'Genindlæs',
	},
	LANGS:{
		LANG:'Oversættelse for sprog:',
		SEND:'Send til publikatoren',
		SAVE:'Gem og test',
		RESET:'Gendan standard sproget',
		REMOVE:'Slet din oversætning',
	},
	HELPTAB5:'Oversættelse',
	ATTACKER:'Angribere',
	DEFENDER:'Forsvarer',
	MSGHIDAT:'angriber',
	MSGHIDDE:'forsvarer',
	MSGATTUNIT:'Hær angreb',
	MSGDEFUNIT:'Hær forsvarere',
	EMOTS:{
		LABEL:'Vil du have flere smilieys?',
		MESS:'Indsæt links til smilieys, hver på en ny linie',
	},
	COMMAND:{
		ALL:'Alle',
		INCOMING:'indkommende',
		OUTGOING:'udgående',
		RETURNING:'retur',
		FORTOWN:'by:',
	},
	BTNSIMUL:'Simulatoren',
	LASTUPDATE:'1488487738325',
	BTNVIEWBB:'BB-KODE',
	MSGSHOWCOST:'Omkostninger ved mistede enheder',
	BBIMG:'enkelt billede',
	POPSOUNDEG:'eksempel: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	RADAR:{
		TOWNFINDER:'Søg byer',
		FIND:'Søg',
		MAXCSTIME:'Maksimal tid',
		MAXUNITTIME:'Maksimal tid',
		BTNFIND:'Søg',
		TOWNNAME:'By',
		UNITTIME:'Time',
		TOWNOWNER:'Ejer',
		BTNSAVEDEFAULT:'Gem værdier som standard',
	},
	QUESTION:'Spørgsmål',
}