RepConvLangArray.sv = {
	AUTHOR:' , Mr. Ferdinand, llavids, Madame GazCar, Rena Rama GazCar',
	BTNCONV:'Omvandla',
	BTNGENER:'Generera',
	BTNVIEW:'Förhandsvisa',
	BTNSAVE:'Spara',
	MSGTITLE:'Omvandla rapport',
	MSGQUEST:'Vilken information vill du publicera?',
	MSGBBCODE:'Efter att ha publicerat din rapport så kan du dela den i forum mm med hjälp utav BBkoden.',
	MSGRESOURCE:'Byte',
	MSGUNITS:'Enheter',
	MSGBUILD:'Byggnader',
	MSGUSC:'Silvermynt förbrukade',
	MSGRAW:'Resurser',
	SUPPORT:'Stödjer',
	SPY:'Spionerar',
	CONQUER:'Erövrade',
	LOSSES:'Förluster',
	HIDDEN:'Dolda',
	NOTUNIT:'[i]Inga[/i]',
	TOWN:'[i]Stad:[/i] ',
	PLAYER:'[i]Spelare:[/i] ',
	ALLY:'[i]Allians:[/i] ',
	CAST:'kasta:',
	ONTOWER:'På staden:',
	MSGHIDAD:'Dölj städer',
	MSGFORUM:'Rapporten kommer att delas',
	BBALLY:'alliansforum / meddelande',
	BBFORUM:'externa forum',
	ICOCLOSE:'Stäng',
	ICOHELP:'Om omvandlaren',
	MSGPREVIEW:'<b>Förhandsvisa Rapport</b>',
	HELPTAB1:'Om',
	HELPTAB2:'Hur fungerar det',
	HELPTAB3:'Ändringar',
	HELPTAB4:'Inställningar',
	MSGHUMAN:{
		OK:'Informationen har sparats',
		ERROR:'Ett problem uppstod vid skrivandet',
		YOUTUBEERROR:'Inkorrekt länk eller ej tillåten att spela utanför youtube',
	},
	LABELS:{
		attack:{
			ATTACKER:'Anfallare',
			DEFENDER:'Försvarare',
			MSGHIDAT:'anfallare',
			MSGHIDDE:'försvarare',
			MSGATTUNIT:'Anfallande armé',
			MSGDEFUNIT:'Försvarande armé',
		},
		support:{
			ATTACKER:'Stöder',
			DEFENDER:'Stödde',
			MSGHIDAT:'Förstärkande stad',
			MSGHIDDE:'Förstärkt stad',
			MSGATTUNIT:'Förstärkande enheter',
			MSGDEFUNIT:'Försvarande enheter',
		},
		espionage:{
			ATTACKER:'Spion',
			DEFENDER:'Spionerade',
			MSGHIDAT:'spion',
			MSGHIDDE:'spionerade',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'kommandoöversikt',
	MSGRETURN:'(återvänd)',
	MSGGENBBCODE:'Genererar en lista med BBkod',
	MSGDEFSITE:'Besegrade...',
	MSGLOSSITE:'Förluster...',
	MSGASATT:'...som anfallare',
	MSGASDEF:'...som försvarare',
	MSGDIFF1:'visa inte skillnader',
	MSGDIFF2:'visa skillnader',
	MSGDIFF3:'visa bara skillnaderna',
	BBCODELIMIT:'Med hänsyn till mängden text som får finnas i ett inlägg så delas informationen upp i grupper vid längre listor. Varje grupp klistras in som ett enskilt inlägg. ',
	CHKPOWERNAME:'Visa tiden som återstår innan du kan använda kraften',
	CHKFORUMTABS:'Ersätt skrollningslisten i forumet för flera rader',
	STATSLINK:'Statistik från',
	BTNSUPPLAYERS:'Lista på spelare',
	CHKUNITSCOST:'Rapporten visar kostnaderna för förlorade enheter',
	CHKOCEANNUMBER:'Visa havets nummer',
	MSGRTLBL:'Information om revolt',
	MSGRTSHOW:'Lägg till information om pågående revolt',
	MSGRTONLINE:'Kommer du vara inloggad under pågående revolt?',
	MSGRTYES:'Ja',
	MSGRTNO:'Nej',
	MSGRTGOD:'Gud',
	MSGRTCSTIME:'KS tid',
	MSGRTONL:'inloggad?',
	MSGRTERR:'Du är i fel stad!<br/>För att hitta information om revolten, gå till stad: ',
	BBTEXT:'textversion',
	BBHTML:'tabbelversion',
	MSG413ERR:'<h3>Den genererade rapporten är för stor.</h3><p>Filtrera bort vissa alternativ för att kunna publicera utan problem</p>',
	CHKREPORTFORMAT:'Generera rapport med hjälp av tabeller',
	WALLNOTSAVED:'Muren är inte sparad',
	WALLSAVED:'Muren är sparad',
	POPSELRECRUNIT:'klicka, för att välja standardenhet för produktion',
	POPRECRUNITTRADE:'klicka, för att fylla i resurser som krävs för att rekrytera vald enhet',
	POPINSERTLASTREPORT:'Klistra in senast omvandlad rapport',
	MSGCOPYREPORT:'Rapporten har sparats. Klicka på [paste_icon] i forum eller ett nytt meddelande för att klistra in',
	POPDISABLEALARM:'Stäng av alarm',
	SOUNDSETTINGS:'Ljudinställningar',
	CHKSOUNDMUTE:'Stäng av ljudet',
	SOUNDVOLUME:'Volym',
	SOUNDURL:'Ljudfil url',
	CHKSOUNDLOOP:'repetera',
	POPSOUNDLOOP:'Spela upp ljudet i en slinga',
	POPSOUNDMUTE:'Stäng av ljudet',
	POPSOUNDPLAY:'Spela med aktuella inställningar',
	POPSOUNDSTOP:'Sluta spela',
	POPSOUNDURL:'URL länk till ljudfilen',
	STATS:{
		PLAYER:'Spelarstatistik',
		ALLY:'Alliansstatistik',
		TOWN:'Stadsstatistik',
		CHKINACTIVE:'Visa inaktiva spelare',
		INACTIVE:'Inaktiv',
		INACTIVEDESC:'Inga poäng för strider eller tillväxt under den tiden',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Truppbyggarverktyg',
			UNITFRAME:'välj din enhet',
			DESCRIPTION1:'I den här staden har du [population] fria invånare',
			DESCRIPTION2:'Vilket räcker för att bygga [max_units]',
			DESCRIPTION3:'Du [yesno] har en [research] framforskad.',
			DESCRIPTION4:'Du kan köa upp till [max_queue] enheter',
			TARGET:'välj vad du vill bygga',
			PACKAGE:'resurser per försändelse (units)',
			BTNSAVE:'spara inställningar',
			TOOLTIPOK:'klicka, för att välja fixerad mängd resurser att skicka',
			TOOLTIPNOTOK:'enheten har inte forskats fram',
			HASRESEARCH:'DU BÖR',
			NORESEARCH:'DU BÖR EJ',
			SETTINGSAVED:'Inställningarna för [city] har sparats',
		},
		RESWND:{
			RESLEFT:'resurser kvar att skicka',
			IMGTOOLTIP:'klicka för att fylla i resurser',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Ny version tillgänglig',
		INSTALL:'Installera',
		REMINDER:'Påminn mig senare',
		REQRELOAD:'Du behöver ladda om sidan',
		RELOAD:'Ladda om sidan',
	},
	LANGS:{
		LANG:'Översättning till språk:',
		SEND:'Skicka för publicering',
		SAVE:'Spara & testa',
		RESET:'Återställ ursprungligt språk',
		REMOVE:'Radera din översättning?',
	},
	HELPTAB5:'Översättning',
	BTNSIMUL:'Simulator',
	EMOTS:{
		LABEL:'Vill du ha fler emotikoner?',
		MESS:'Klistra in länk till emotikon, separera med ny rad',
	},
	COMMAND:{
		ALL:'Alla',
		INCOMING:'inkommande',
		OUTGOING:'utgående',
		RETURNING:'återvändande',
		FORTOWN:'stad:',
	},
	BTNVIEWBB:'BBkod',
	MSGSHOWCOST:'Kostnad för förlorade enheter',
	BBIMG:'enskild bild',
	POPSOUNDEG:'Exempel: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	RADAR:{
		TOWNFINDER:'Sök städer',
		FIND:'Sök',
		MAXCSTIME:'Maximal restid för koloniskepp',
		BTNFIND:'Sök',
		TOWNNAME:'Stad',
		CSTIME:'Ks tid',
		TOWNOWNER:'Ägare',
		TOWNRESERVED:'Reservering',
		TOWNPOINTS:'Minsta stadspoäng',
		BTNSAVEDEFAULT:'Spara värden som default',
		ALL:'Vilken stad som helst',
	},
	WALL:{
		LISTSAVED:'Muren sparad på datum',
	},
	QUESTION:'Fråga',
	TSL:{
		WND:{
			WINDOWTITLE:'Lista sorterad på stadsnamn',
		},
	},
	CHKOLDTRADE:'Används gamla bytesutseende',
	AO:{
		TITLE:'Akademi översikt',
	},
	MOBILEVERSION:'Mobil version',
	LASTUPDATE:'1487501824228',
}