RepConvLangArray.cs = {
	INFO:{
		0:'Potusek',
		1:'grepolis@potusek.eu',
	},
	WEBSITE:'Web',
	AUTHOR:'tomthas@seznam.cz, Thasoss, Apic',
	BTNCONV:'Konvertovat',
	BTNGENER:'Vytvořit',
	BTNSRC:'Zdroj',
	BTNVIEW:'Náhled',
	BTNSAVE:'Uložit',
	BTNMARKS:'Označit jako přečtené',
	BTNMARKA:'Označit vše jako přečtené',
	MSGTITLE:'Konvertovat hlášení',
	MSGQUEST:'Jaká data mají být zobrazena?',
	MSGALL:'Vše',
	MSGBBCODE:'Následující publikaci hlášení můžete za pomoci BB kódů vkládat do zpráv či fóra.',
	MSGRESOURCE:'Kořist',
	MSGUNITS:'Jednotky',
	MSGBUILD:'Budovy',
	MSGUSC:'Použité stříbrné mince',
	MSGRAW:'Suroviny',
	SUPPORT:'Podpora',
	SPY:'Špehování',
	CONQUER:'Dobyto',
	LOSSES:'Ztráty',
	HIDDEN:'Skryté',
	NOTUNIT:'[i]Žádný[/i]',
	TOWN:'[i]Město:[/i] ',
	PLAYER:'[i]Hráč:[/i] ',
	ALLY:'[i]Ali:[/i] ',
	CAST:'seslat:',
	ONTOWER:'Na město:',
	MSGHIDAD:'Skrýt města',
	MSGFORUM:'Hlášení bude publikováno',
	BBALLY:'alianční fóra / zprávy',
	BBFORUM:'externí fórum',
	ERRGETSRC:'Došlo k chybě! Prosím, ohlaste to na:  potusek@westtax.info',
	ICOCLOSE:'Zavřít',
	ICOHELP:'O konvertoru',
	MSGPREVIEW:'<b>Náhled hlášení</b>',
	HELPTAB1:'O...',
	HELPTAB2:'Jak to funguje',
	HELPTAB3:'Změny',
	HELPTAB4:'Nastavení',
	HLPVERSION:'Verze',
	HLPFIXED:'Fixed',
	HLPADDED:'Přidáno',
	MSGHUMAN:{
		OK:'Informace uloženy',
		ERROR:'Při zapisování nastala chyba!',
		YOUTUBEERROR:'Špatně vložení link nebo není povoleno přehrání mimo Youtube',
	},
	STATSPOINT:'Body',
	STATSRANK:'Umístění',
	LABELS:{
		attack:{
			ATTACKER:'Útočník',
			DEFENDER:'Obránce',
			MSGHIDAT:'útočník',
			MSGHIDDE:'obránce',
			MSGATTUNIT:'Útočící vojsko',
			MSGDEFUNIT:'Bránící vojsko',
		},
		support:{
			ATTACKER:'Podporující',
			DEFENDER:'Podpořený',
			MSGHIDAT:'podporující',
			MSGHIDDE:'podpořený',
			MSGATTUNIT:'Podporující vojsko',
			MSGDEFUNIT:'Vojsko obránce',
		},
		espionage:{
			ATTACKER:'Špeh',
			DEFENDER:'Špehovaný',
			MSGHIDAT:'špeh',
			MSGHIDDE:'špehovaný',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'podrobnosti o příkazu',
	MSGRETURN:'(návrat)',
	MSGCLAIM:'Rezervace města',
	MSGCLAIMPPUP:'Vytvořit rezervaci',
	MSGGENBBCODE:'Vytvořit seznam v BB kódu',
	MSGDEFSITE:'Poražený...',
	MSGLOSSITE:'Ztráty...',
	MSGASATT:'...jako útočník',
	MSGASDEF:'...jako obránce',
	MSGDIFF1:'neukázat rozdíly',
	MSGDIFF2:'ukázat rozdíly',
	MSGDIFF3:'ukázat jen rozdíly',
	BBCODELIMIT:'V případě překročení počtu znaků na jeden příspěvek jsou skupiny odděleny. Každá skupina je oddělena samostatně.',
	CHKPOWERNAME:'Zobrazit čas zbývající do možnosti seslat kouzlo',
	CHKNIGHTNAME:'Skrýt města v nočním bonusu',
	CHKFORUMTABS:'Nahrazení posuvníku záložek na fóru za vícero řad',
	BTNRESERVE:'Rezervace',
	LNKRESERVE:'Rezervace',
	LBLGETRESER:'Získávání dat ...',
	BTNCHECK:'Kontrolování rezervací',
	CHKCMDIMG:'Vidět ikony příkazů u cílových měst',
	STATSLINK:'Statistiky zobrazovat z',
	BTNSUPPLAYERS:'Seznam hráčů',
	CHKUNITSCOST:'Hlášení ukazuje cenu padlých jednotek',
	CHKOCEANNUMBER:'Zobrazit čísla moří',
	MSGRTLBL:'Informace o vzpouře',
	MSGRTSHOW:'Přidat informace o vzpouře',
	MSGRTONLINE:'Budeš online během běžící vzpoury?',
	MSGRTYES:'Ano',
	MSGRTNO:'Ne',
	MSGRTGOD:'Bůh',
	MSGRTCSTIME:'Čas kol. lodě',
	MSGRTONL:'Online?',
	MSGRTERR:'Jsi ve špatném městě!<br/>Pro vytvoření informací o vzpouře přejdi na správné město: ',
	BBTEXT:'textová verze',
	BBHTML:'tabulková verze',
	MSG413ERR:'<h3>Vytvořené hlášení je příliš velké.</h3><p>Využij dostupných možností pro bezproblémové zredukování velikosti.</p>',
	CHKREPORTFORMAT:'Hlášení v tabulkách',
	WALLNOTSAVED:'Hradby nejsou uloženy',
	WALLSAVED:'Hradby jsou uloženy',
	POPSELRECRUNIT:'klikni pro zvolení výchozí produkované jednotky',
	POPRECRUNITTRADE:'klikni pro doplnění potřebných surovin k rekrutaci zvolené jednotky',
	POPINSERTLASTREPORT:'Vložit naposledy konvertové hlášení',
	MSGCOPYREPORT:'Hlášení uloženo. Klikni, prosím na [paste_icon] v okně fóra či zpráv pro vložení.',
	POPDISABLEALARM:'Vypnout alarm',
	SOUNDSETTINGS:'Nastavení zvuku',
	CHKSOUNDMUTE:'Ztlumit',
	SOUNDVOLUME:'Hlasitost',
	SOUNDURL:'URL souboru',
	CHKSOUNDLOOP:'Opakovaně',
	POPSOUNDLOOP:'Přehrávat opakovaně',
	POPSOUNDMUTE:'Ztlumit zvuk',
	POPSOUNDPLAY:'Spustit se současným nastavením',
	POPSOUNDSTOP:'Zastavit přehrávání',
	POPSOUNDURL:'URL cesta k souboru se zvukem',
	STATS:{
		PLAYER:'Stats hráče',
		ALLY:'Stats aliance',
		TOWN:'Stats města',
		INACTIVE:'Neaktivní',
		CHKINACTIVE:'Ukázat neaktivní hráče',
		INACTIVEDESC:'Za tento čas nedošlo k nárůstu bitevních ani stavebních bodů.',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Pomocník s rekrutováním',
			UNITFRAME:'zvol jednotku',
			DESCRIPTION1:'V tomto městě máš [population] volné populace',
			DESCRIPTION2:'Dostatek surovin pro stavbu [max_units]',
			DESCRIPTION3:'[yesno] máš [research] vyzkoumán.',
			DESCRIPTION4:'Do fronty lze zařadit maximálně [max_queue] jednotek',
			TARGET:'Zvol cílový počet',
			PACKAGE:'Množství surovin na zásilku (jednotky)',
			BTNSAVE:'Uložit nastavení',
			TOOLTIPOK:'klikni pro zvolení výchozí jednotky, na kterou budou posílány suroviny',
			TOOLTIPNOTOK:'jednotka nebyla vyzkoumána',
			HASRESEARCH:'ANO',
			NORESEARCH:'NE',
			SETTINGSAVED:'Nastavení pro [city] bylo uloženo',
		},
		RESWND:{
			RESLEFT:'suroviny odeslány',
			IMGTOOLTIP:'klikni pro naplnění surovinami',
		},
	},
	NEWVERSION:{
		AVAILABLE:'K dispozici nová verze',
		REMINDER:'Připomenout později',
		REQRELOAD:'Požadováno obnovení stránky',
		RELOAD:'Obnovit',
		INSTALL:'Instalovat',
	},
	LANGS:{
		LANG:'Překlad pro jazyk:',
		SEND:'Poslat ke zveřejnění',
		SAVE:'Uložit & testovat',
		RESET:'Vrátit k výchozímu jazyku',
		REMOVE:'Smazat Váš překlad?',
	},
	HELPTAB5:'Překlad',
	BTNSIMUL:'Simulátor',
	EMOTS:{
		MESS:'Vložte odkazy na emotikony, každý na novou řádku.',
		LABEL:'Chcete více emotikonů?',
	},
	COMMAND:{
		ALL:'Vše',
		FORTOWN:'Město:',
		INCOMING:'Příchozí',
		OUTGOING:'Odchozí',
		RETURNING:'Vracející se',
	},
	RADAR:{
		TOWNFINDER:'Hledat města',
		FIND:'Hledat',
		MAXCSTIME:'Maximální dojezd kol. lodě',
		BTNFIND:'Hledat',
		TOWNNAME:'Město',
		CSTIME:'Čas kol. lodě',
		TOWNOWNER:'Majitel',
		TOWNRESERVED:'Rezervace',
		TOWNPOINTS:'Minimální počet bodů',
		BTNSAVEDEFAULT:'Uložit hodnoty jako výchozí',
		ALL:'Jakékoliv město',
	},
	LASTUPDATE:'1487459559463',
	BTNVIEWBB:'BB kód',
	MSGSHOWCOST:'Cena padlých jednotek',
	WALL:{
		LISTSAVED:'Uloženo na hradbách dne',
		LISTSTATE:'Stav pro hradby z dne',
		DELETECURRENT:'Smazat současný záznam',
		WANTDELETECURRENT:'Chceš odstranit současný záznam hradeb?',
	},
	QUESTION:'Dotaz',
	TSL:{
		WND:{
			WINDOWTITLE:'Seznam seřazených měst',
			TOOLTIP:'ukázat zařazené město',
		},
	},
	CHKOLDTRADE:'Použít staré rozvržení obchodu',
	AO:{
		TITLE:'Přehled akademie',
	},
	BBIMG:'jeden obrázek',
	POPSOUNDEG:'například: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	MOBILEVERSION:'Mobilní verze',
}