RepConvLangArray.en = {
    AUTHOR:'Potusek, Anpu, BentleyJ, Lascaux',
    BTNCONV:'Convert',
    BTNGENER:'Generate',
    BTNVIEW:'Preview',
    BTNSAVE:'Save',
    BTNVIEWBB:'BBCode',
    MSGTITLE:'Convert report',
    MSGQUEST:'Which of the data do you want to publish?',
    MSGBBCODE:'Following the publication of the report, you can pair it with news and forums using the BBCode.',
    MSGRESOURCE:'Loot',
    MSGUNITS:'Units',
    MSGBUILD:'Buildings',
    MSGUSC:'Silver coins used',
    MSGRAW:'Raw materials',
    MSGSHOWCOST:'Costs of lost units',
    SUPPORT:'Support',
    SPY:'Spying',
    CONQUER:'Conquered',
    LOSSES:'Losses',
    HIDDEN:'Hidden',
    NOTUNIT:'[i]None[/i]',
    TOWN:'[i]Town:[/i] ',
    PLAYER:'[i]Player:[/i] ',
    ALLY:'[i]Ally:[/i] ',
    CAST:'cast:',
    ONTOWER:'On the town:',
    MSGHIDAD:'Hide cities',
    MSGFORUM:'The report will be published',
    BBALLY:'alliance forums / in the message',
    BBFORUM:'external forum',
    ICOCLOSE:'Close',
    ICOHELP:'About converter',
    MSGPREVIEW:'<b>Report preview</b>',
    HELPTAB1:'About',
    HELPTAB2:'How does it work',
    HELPTAB3:'Changes',
    HELPTAB4:'Settings',
    HELPTAB6:'Donations',
    MSGHUMAN:{
        OK:'The information has been saved',
        ERROR:'An error occurred while writing',
		YOUTUBEERROR: 'Incorrect link or not allowed to play outside youtube',
    },
    LABELS:{
        attack:{
            ATTACKER:'Attacker',
            DEFENDER:'Defender',
            MSGHIDAT:'attacker',
            MSGHIDDE:'defender',
            MSGATTUNIT:'Army attacking',
            MSGDEFUNIT:'Army defenders',
        },
        support:{
            ATTACKER:'Supporting',
            DEFENDER:'Supported',
            MSGHIDAT:'supporting',
            MSGHIDDE:'supported',
            MSGATTUNIT:'Army supporting',
            MSGDEFUNIT:'Army defenders',
        },
        espionage:{
            ATTACKER:'Spy',
            DEFENDER:'Spied',
            MSGHIDAT:'spy',
            MSGHIDDE:'spied',
            MSGATTUNIT:'',
            MSGDEFUNIT:'',
        },
    },
    MSGDETAIL:'command details',
    MSGRETURN:'(return)',
    MSGGENBBCODE:'Generate a list of BBCode',
    MSGDEFSITE:'Defeated...',
    MSGLOSSITE:'Losses...',
    MSGASATT:'...as an attacker',
    MSGASDEF:'...as a defender',
    MSGDIFF1:'do not show differences',
    MSGDIFF2:'show differences',
    MSGDIFF3:'show only the differences',
    BBCODELIMIT:'In view of the limited amount of text in one post, in the case of a long list, the data were divided into groups. Each group paste as a separate entry.',
    CHKPOWERNAME:'Display time remaining to the possibility of using the spell',
    CHKFORUMTABS:'Replace scrolling tabs on the forum for multi line',
    STATSLINK:'View statistics from',
    BTNSUPPLAYERS:'List of players',
    CHKUNITSCOST:'The report showing the cost of lost units',
    CHKOCEANNUMBER:'Display ocean numbers',
    MSGRTLBL:'Revolt information',
    MSGRTSHOW:'Add ongoing revolt information',
    MSGRTONLINE:'Are you going to be online during red revolt?',
    MSGRTYES:'Yes',
    MSGRTNO:'No',
    MSGRTGOD:'God',
    MSGRTCSTIME:'CS time',
    MSGRTONL:'online?',
    MSGRTERR:'You are in a wrong city!<br/>To create revolt information, please go to city: ',
    BBTEXT:'text version',
    BBHTML:'table version',
    BBIMG:'single image',
    MSG413ERR:'<h3>The generated report is too large.</h3><p>Use the available options and reduce to publish without problems.</p>',
    CHKREPORTFORMAT:'Generate reports using tables',
    WALLNOTSAVED:'Wall is not saved',
    WALLSAVED:'Wall is saved',
    POPSELRECRUNIT:'click, to select default production unit',
    POPRECRUNITTRADE:'click, to fill in resources needed to recruit selected unit',
    POPINSERTLASTREPORT:'Paste the last converted report',
    MSGCOPYREPORT:'The report has been saved. Please click [paste_icon] on forums or new message window to paste it',
    POPDISABLEALARM:'Disable alarm',
    SOUNDSETTINGS:'Sound settings',
    CHKSOUNDMUTE:'Mute',
    SOUNDVOLUME:'Volume',
    SOUNDURL:'Sound file url',
    CHKSOUNDLOOP:'loop',
    POPSOUNDLOOP:'Play in the loop',
    POPSOUNDMUTE:'Mute the sound',
    POPSOUNDPLAY:'Play with current settings',
    POPSOUNDSTOP:'Stop playng',
    POPSOUNDURL:'Url path to the file with sound',
	POPSOUNDEG:'example: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
    STATS:{
        PLAYER:'Player stats',
        ALLY:'Alliance stats',
        TOWN:'Town stats',
        INACTIVE:'Inactive',
        CHKINACTIVE : 'Show inactive players',
		INACTIVEDESC : 'At that time there was no point fighting and expansion',
    },
    ABH:{
        WND:{
            WINDOWTITLE:'Army Builder Helper',
            UNITFRAME:'choose your unit',
            DESCRIPTION1:'In this city, you have [population] free population',
            DESCRIPTION2:'Which is enough to build [max_units]',
            DESCRIPTION3:'You [yesno] have a [research] researched.',
            DESCRIPTION4:'You can queue up maximum of [max_queue] units',
            TARGET:'choose your build target',
            PACKAGE:'resource package per shipment (units)',
            BTNSAVE:'save settings',
            TOOLTIPOK:'click, to select default unit for which you\'ll be sending resources',
            TOOLTIPNOTOK:'unit has not been researched',
            HASRESEARCH:'DO',
            NORESEARCH:'DO NOT',
            SETTINGSAVED:'Settings for [city] have been saved',
        },
        RESWND:{
            RESLEFT:'resources left to send',
            IMGTOOLTIP:'click, to fill in resources',
        },
    },
    NEWVERSION:{
        AVAILABLE:'New version available',
        INSTALL:'Install',
        REMINDER:'Remind me later',
        REQRELOAD:'Refresh required',
        RELOAD:'Refresh',
    },
    LANGS:{
        LANG:'Translation for language:',
        SEND:'Send to publication',
        SAVE:'Save & test',
        RESET:'Restore the default language',
        REMOVE:'Delete your translation?',
    },
    HELPTAB5:'Translation',
    BTNSIMUL:'Simulator',
    EMOTS : {
        LABEL: "Do you want more emoticon?",
        MESS:  "Paste links to emoticon, each on a new line"
    },
    COMMAND : {
        ALL: "All",
        INCOMING: "incoming",
        OUTGOING: "outgoing",
        RETURNING: "returning",
        FORTOWN : "town:"
    },
    RADAR :{
        TOWNFINDER: "Search cities",
        FIND: "Search",
        MAXCSTIME:"Maximum time",
        MAXUNITTIME:"Maximum time",
        BTNFIND: "Search",
        TOWNNAME: "Town",
        CSTIME: "CS time",
        UNITTIME: "time",
        TOWNOWNER: "Owner",
        TOWNRESERVED: "Reservation",
        TOWNPOINTS: "Minimal town points",
        BTNSAVEDEFAULT: "Save values as default",
        ALL: "Any town",
        SHOWCITIES: "Show cities"
    },
    WALL : {
        LISTSAVED : 'Saved on the wall the day',
        LISTSTATE : 'Condition of the wall on the day',
        DELETECURRENT : 'Delete the current record',
        WANTDELETECURRENT : 'Do you want to delete the current record of the wall?'
    },
    QUESTION : 'Question',
    TSL:{
    	WND:{
    		WINDOWTITLE:'Towns Sorted List',
    		TOOLTIP:'show sorted town'
    	}
    },
    CHKOLDTRADE : 'Use old trade layout',
    AO:{
	TITLE: 'Academy Overview'
    },
	MOBILEVERSION: 'Mobile version',
    CHKWONDERTRADE : 'When sending resources for world wonders, send maximum equal amounts',
    CHKTOWNPOPUP : 'Display troop info tooltip when hovering over city name on drop-down city list',
    POPWONDERSHOT : 'Amount of available construction accelerations',
    CHKTACL : 'Enable commands list movement',
    BTNCOMPARE : 'Pact vs Enemy',
    ALLYCOMPARETITLE: 'Comparison of allied forces vs enemy alliances',
    CHKMCOL : 'Color messages according to the pre-set color scheme',
    CHKBUPO : 'Display build points',
    CHKMOUSEWHEELZOOMBULLEYE: 'Use mouse wheel to zoom map',
    POPINSERTEMOT: 'Insert the emoticon',
    CHKIMGBTN: 'Display the octopus on the GRCRTools buttons',
    POPSITUATIONALCITYREPORT:'Situation report',
    CHKSCTUNITS:'Units in the city',
    CHKSCTPREMIUM:'Premium options',
    CHKSCTSILVER:'Amount of silver in the cave',
    CHKSCTINCSUPP:'Number of incoming supports',
    CHKSCTINCSATT:'Number of incoming attacks',
    OLYMPOWNER:'Owner', 
    OLYMPTROOP:'Troops in the temple', 
    OLYMPACCOM:'Active commands on this Temple', 
    OLYMPDESC:'Temple description'

}