RepConvLangArray.de = {
	INFO:{
		0:'Potusek',
		1:'grepolis@potusek.eu',
	},
	WEBSITE:'Strona domowa',
	AUTHOR:'Kartuga-Chipssi1@gmx.net, Lupo22, Jordan06, Gliese 558, Luccer',
	BTNCONV:'Konvertieren',
	BTNGENER:'Generieren',
	BTNSRC:'Quelle',
	BTNVIEW:'Vorschau',
	BTNSAVE:'Speichern',
	BTNMARKS:'Als gelesen markieren',
	BTNMARKA:'Markieren Sie alle als gelesen',
	MSGTITLE:'Konvertiere den Report',
	MSGQUEST:'Welche Daten willst du veröffentlichen?',
	MSGALL:'Alle',
	MSGBBCODE:'Nach der Veröffentlichung des Berichts kannst du die News in internen und externen Foren veröffentlichen.',
	MSGRESOURCE:'Beute',
	MSGUNITS:'Einheiten',
	MSGBUILD:'Gebäude',
	MSGUSC:'Verwendete Silbermünzen',
	MSGRAW:'Rohstoffe',
	SUPPORT:'Unterstützung',
	SPY:'Spionage',
	CONQUER:'Erobert',
	LOSSES:'Verluste',
	HIDDEN:'Versteckt',
	NOTUNIT:'[i]Keine[/i]',
	TOWN:'[i]Stadt:[/i] ',
	PLAYER:'[i]Spieler:[/i] ',
	ALLY:'[i]Allianz:[/i] ',
	CAST:'Besetzung:',
	ONTOWER:'In der Stadt:',
	MSGHIDAD:'Städte ausblenden',
	MSGFORUM:'Der Bericht wird veröffentlicht',
	BBALLY:'Allianz Forum / in Nachrichten',
	BBFORUM:'Externes Forum',
	ERRGETSRC:'Ist ein Fehler aufgetreten! Bitte, generiere mir die Quelle und senden Sie als Anhang an die Adresse potusek@westtax.info',
	ICOCLOSE:'Schließen',
	ICOHELP:'Über den Konverter',
	MSGPREVIEW:'<b>Bericht-Vorschau</b>',
	HELPTAB1:'Über',
	HELPTAB2:'Wie funktioniert es?',
	HELPTAB3:'Änderungen',
	HELPTAB4:'Einstellungen',
	HLPVERSION:'Version',
	HLPFIXED:'Fixed',
	HLPADDED:'Added',
	MSGHUMAN:{
		OK:'Die Informationen wurden gespeichert',
		ERROR:'Fehler beim Schreiben',
		YOUTUBEERROR:'Fehlerhafter Link oder nicht außerhalb von Youtube erlaubt abzuspielen',
	},
	STATS:'Player stats',
	STATSPOINT:'Points',
	STATSRANK:'Rank',
	LABELS:{
		attack:{
			ATTACKER:'Angreifer',
			DEFENDER:'Verteidiger',
			MSGHIDAT:'Angreifer',
			MSGHIDDE:'Verteidiger',
			MSGATTUNIT:'Armee angreifer',
			MSGDEFUNIT:'Armee verteidiger',
		},
		support:{
			ATTACKER:'Unterstützung',
			DEFENDER:'Unterstützte',
			MSGHIDAT:'tragende',
			MSGHIDDE:'unterstützt',
			MSGATTUNIT:'Armee Unterstützung',
			MSGDEFUNIT:'Armee Verteidigung',
		},
		espionage:{
			ATTACKER:'Spion',
			DEFENDER:'spioniert',
			MSGHIDAT:'spionieren',
			MSGHIDDE:'ausspionierte Stadt',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'Befehl Details',
	MSGRETURN:'(rückkehr)',
	MSGCLAIM:'Reservierte Stadt',
	MSGCLAIMPPUP:'Generieren Reservation',
	MSGDEFSITE:'Besiegt...',
	MSGLOSSITE:'Verluste...',
	MSGASATT:'...als Angreifer',
	MSGASDEF:'...als Verteidiger',
	MSGDIFF:'zeige unterschiede',
	MSGDIFF1:'zeige keine Unterschiede',
	MSGDIFF2:'Zeige Unterschiede',
	MSGDIFF3:'zeige nur die Unterschiede',
	BBCODELIMIT:'In Anbetracht der begrenzten Menge des Textes in einem Pfosten, im Falle einer langen Liste, wurden die Daten in Gruppen aufgeteilt. Jede Gruppe wird als separater Eintrag eingefügt.',
	CHKPOWERNAME:'Zeigt die verbleibende Zeit auf die Möglichkeit der Verwendung des Zaubers',
	CHKFORUMTABS:'Ersetzt das blättern Forum Reiter werden in 2 Reihen angezeigt',
	BTNRESERVE:'Booking',
	LNKRESERVE:'Reservierungen',
	LBLGETRESER:'Erste Daten ...',
	BTNCHECK:'Überprüfen Vorbehalte',
	CHKCMDIMG:'View the icons for the destination city commands',
	STATSLINK:'Statistiken anzeigen über',
	BTNSUPPLAYERS:'Liste der Spieler',
	CHKUNITSCOST:'Im Bericht werden die Kosten für verlorene Einheiten angezeigt',
	CHKOCEANNUMBER:'Display numbers seas',
	MSGRTYES:'Ja',
	MSGRTNO:'Nein',
	MSGGENBBCODE:'Erstelle die Liste als BBCode',
	BBTEXT:'Text-Version',
	BBHTML:'Tabellen-Version',
	WALLNOTSAVED:'Die Stadtmauer ist nicht gespeichert',
	WALLSAVED:'Die Stadtmauer ist gespeichert',
	POPINSERTLASTREPORT:'Einfügen vom letzten erstellten Bericht',
	POPDISABLEALARM:'Alarm ausschalten',
	SOUNDSETTINGS:'Sound Einstellungen',
	ABH:{
		WND:{
			UNITFRAME:'Einheit wählen',
			DESCRIPTION1:'Du hast in dieser Stadt [population] freie Bevölkerung',
			BTNSAVE:'Einstellungen speichern',
			SETTINGSAVED:'Einstellungen für [city] wurden gespeichert',
			DESCRIPTION2:'Das reicht für den Bau von [max_units]',
			DESCRIPTION3:'Die Forschung [research] [yesno] erforscht.',
			HASRESEARCH:'IST',
			NORESEARCH:'IST NICHT',
			DESCRIPTION4:'Es können [max_queue] Einheiten gebaut werden.',
			WINDOWTITLE:'Armee aufbauen',
			TARGET:'wähle deine Bauziel',
			PACKAGE:'Rohstoff-Paket pro Sendung (Einheiten)',
			TOOLTIPOK:'Klicken, um die standardmäßige Einheit auszuwählen, für die du Rohstoffe sendest',
			TOOLTIPNOTOK:'Einheit nicht erforscht',
		},
		RESWND:{
			IMGTOOLTIP:'Klicken, um Rohstoffe einzufügen',
			RESLEFT:'Übrige Rohstoff zum senden',
		},
	},
	NEWVERSION:{
		REMINDER:'später erinnern',
		AVAILABLE:'Neue Version verfügbar',
		INSTALL:'Installieren',
		REQRELOAD:'Aktualisierung erforderlich',
		RELOAD:'Aktualisierung ',
	},
	LANGS:{
		LANG:'Übersetzung in Sprache:',
		REMOVE:'Deine Übersetzung löschen?',
		RESET:'Auf standardmäßige Sprache zurücksetzen',
		SAVE:'Speichern & Testen',
		SEND:'Senden zum Veröffentlichen',
	},
	HELPTAB5:'Übersetzung',
	POPSOUNDURL:'Url Pfad zur Musik-Datei',
	SOUNDVOLUME:'Lautstärke',
	MSGCOPYREPORT:'Der Bericht wurde gespeichert.Click [paste_icon] um den Bericht im Forum oder einer Nachricht einzufügen.',
	POPSOUNDSTOP:'Wiedergabe stoppen',
	MSGSHOWCOST:'Kosten für verlorene Einheiten',
	MSGRTLBL:'Revolte Informationen',
	MSGRTSHOW:'hinzufügen eingehende Revolte Informationen',
	MSGRTONLINE:'Werden Sie während der roten Revolte online sein?',
	MSGRTGOD:'Gott',
	MSGRTCSTIME:'CS Zeit',
	MSGRTONL:'Online?',
	MSGRTERR:'Sie befinden sich in der falschen Stadt!<br/>Um Informationen über die Revolte zu erstellen, gehe bitte zur Stadt: ',
	MSG413ERR:'<h3>Der generierte Bericht ist zu groß.</h3><p>Verwende die verfügbaren Optionen zum reduzieren und um ohne Probleme zu veröffentlichen.</p>',
	CHKREPORTFORMAT:'Erstellen Sie Berichte mit Hilfe von Tabellen',
	POPSELRECRUNIT:'Klicken, um Standard-Produktionseinheit zu wählen',
	CHKSOUNDMUTE:'Stumm',
	SOUNDURL:'Musik-Datei URL',
	CHKSOUNDLOOP:'Schleife',
	POPSOUNDLOOP:'Spiele in Schleife ab',
	POPSOUNDMUTE:'Schalte den Ton stumm',
	POPSOUNDPLAY:'Spiele mit den aktuellen Einstellungen',
	EMOTS:{
		LABEL:'Willst du mehr Emoticons?',
		MESS:'Link einfügen zu Emoticon, jeden in einer neuen Zeile.',
	},
	COMMAND:{
		ALL:'Alles',
		INCOMING:'Eingehend',
		OUTGOING:'Ausgehend',
		RETURNING:'Rückkehr',
		FORTOWN:'Stadt:',
	},
	RADAR:{
		TOWNFINDER:'Suche Städte',
		FIND:'Suchen',
		MAXCSTIME:'Maximale Zeit Kolonieschiff',
		BTNFIND:'Suchen',
		TOWNNAME:'Stadt',
		CSTIME:'Zeit Kolonieschiff ',
		TOWNOWNER:'Besitzer',
		TOWNRESERVED:'Reservierung',
		TOWNPOINTS:'Minimale Stadtpunkte',
		BTNSAVEDEFAULT:'Werte als Standard speichern',
		ALL:'Jede Stadt',
	},
	TSL:{
		WND:{
			TOOLTIP:'zeige Sortiert nach Ort',
			WINDOWTITLE:'Städte Liste sortiert',
		},
	},
	QUESTION:'Frage',
	WALL:{
		LISTSAVED:'Gespeichert auf der Mauer der Tag',
		LISTSTATE:'Beschaffenheit der Mauer an dem Tag',
		DELETECURRENT:'Lösche den aktuellen Datensatz',
		WANTDELETECURRENT:'Möchtest du den aktuellen Speicherstand der Mauer entfernen?',
	},
	CHKWONDERTRADE:'Wenn Resourcen für Weltwunder gesendet werden, sende den maximal möglichen Betrag',
	MOBILEVERSION:'Mobile Version',
	AO:{
		TITLE:'Akademie Überblick',
	},
	CHKOLDTRADE:'Altes Layout verwenden',
	POPSOUNDEG:'Beispiel: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	POPRECRUNITTRADE:'Klicken, um fehlende Rohstoffe für die Rekrutierung der ausgewählten Einheit auszufüllen',
	BBIMG:'Einzelnes Bild',
	LASTUPDATE:'1487463932539',
}