RepConvLangArray.es = {
	INFO:{
		0:'Potusek',
		1:'grepolis@potusek.eu',
	},
	WEBSITE:'Website',
	AUTHOR:'katralba@gmail.com, JONUSEJ, Shirowashi, fitidel, kaito edogawa',
	BTNCONV:'Convertir',
	BTNGENER:'Generar',
	BTNSRC:'Fuente',
	BTNVIEW:'Visualizar',
	BTNSAVE:'Guardar',
	BTNMARKS:'Marcarlo como leído',
	BTNMARKA:'Marcar todo como leído',
	MSGTITLE:'Convertir reporte',
	MSGQUEST:'¿Qué datos desea publicar?',
	MSGALL:'Todo',
	MSGBBCODE:'Una vez publicado el reporte, se puede anexar al foro utilizando código BB.',
	MSGRESOURCE:'Saquear',
	MSGUNITS:'Unidades',
	MSGBUILD:'Edificios',
	MSGUSC:'Monedas utilizadas',
	MSGRAW:'Materias primas',
	SUPPORT:'Soporte',
	SPY:'Espionaje',
	CONQUER:'Conquistado',
	LOSSES:'Pérdidas',
	HIDDEN:'Escondido',
	NOTUNIT:'[i]Nada[/i]',
	TOWN:'[i]Ciudad:[/i] ',
	PLAYER:'[i]Jugador:[/i] ',
	ALLY:'[i]Alianza:[/i] ',
	CAST:'echar:',
	ONTOWER:'En la ciudad:',
	MSGHIDAD:'Esconder ciudades',
	MSGFORUM:'El reporte se publicará',
	BBALLY:'foro de la alianza / en el mensaje',
	BBFORUM:'foro externo',
	ERRGETSRC:'¡Ha habido un error! Por favor, generar el fuente y enviarlo como anexo a  potusek@westtax.info',
	ICOCLOSE:'Cerrar',
	ICOHELP:'Acerca del convertidor',
	MSGPREVIEW:'<b>Previsualización de informe</b>',
	HELPTAB1:'Acerca de',
	HELPTAB2:'Cómo funciona',
	HELPTAB3:'Cambios',
	HELPTAB4:'Configuración',
	HLPVERSION:'Modificación',
	HLPFIXED:'Corregido',
	HLPADDED:'Añadido',
	MSGHUMAN:{
		OK:'La información se ha guardado',
		ERROR:'Error al escribir',
		YOUTUBEERROR:'Link incorrecto o no autorizada la reproducción fuera de Youtube',
	},
	STATS:'Estadísticas del jugador',
	STATSPOINT:'Puntos',
	STATSRANK:'Rango',
	LABELS:{
		attack:{
			ATTACKER:'Atacante',
			DEFENDER:'Defensor',
			MSGHIDAT:'atacante',
			MSGHIDDE:'defensor',
			MSGATTUNIT:'Ejército atacante',
			MSGDEFUNIT:'Ejército defensor',
		},
		support:{
			ATTACKER:'Apoyador',
			DEFENDER:'Apoyado',
			MSGHIDAT:'apoyador',
			MSGHIDDE:'apoyado',
			MSGATTUNIT:'Ejército de apoyo',
			MSGDEFUNIT:'Ejército apoyado',
		},
		espionage:{
			ATTACKER:'Espía',
			DEFENDER:'Espiado',
			MSGHIDAT:'espía',
			MSGHIDDE:'espiado',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'Detalles del comando',
	MSGRETURN:'(volver)',
	MSGCLAIM:'reservas de ciudades',
	MSGCLAIMPPUP:'Generar la reserva',
	MSGGENBBCODE:'Generar una lista de código BBC',
	MSGDEFSITE:'Derrotado...',
	MSGLOSSITE:'Pérdidas...',
	MSGASATT:'...como atacante',
	MSGASDEF:'...como defensor',
	MSGDIFF1:'no mostrar las diferencias',
	MSGDIFF2:'mostrar las diferencias',
	MSGDIFF3:'mostrar sólo las diferencias',
	BBCODELIMIT:'En vista de la cantidad limitada de texto en un mensaje, si hay una lista larga, se dividirá en partes. Cada parte cuenta como una entidad separada.',
	CHKPOWERNAME:'Mostrar el tiempo restante hasta el próximo hechizo',
	CHKNIGHTNAME:'Oscurece la ciudad en el bono nocturno',
	CHKFORUMTABS:'Reemplazar los desplazamientos de las pestañas del foro por multi-línea',
	BTNRESERVE:'Anotando',
	LNKRESERVE:'Reservas',
	LBLGETRESER:'Obteniendo los datos ...',
	BTNCHECK:'Verificando las  reservas',
	CHKCMDIMG:'View the icons for the destination city commands',
	STATSLINK:'Estadísticas en pantalla',
	BTNSUPPLAYERS:'Lista de jugadores',
	CHKUNITSCOST:'El informe muestra el coste de las unidades perdidas',
	CHKOCEANNUMBER:'Mostrar números de mares',
	MSGRTGOD:'Dios',
	MSGRTYES:'Si',
	MSGRTONLINE:'¿Estarás conectado durante el puño rojo?',
	MSGRTLBL:'Información de la revuelta',
	MSGRTERR:'¡Estás en una ciudad equivocada!<br/>Para crear información de la revuelta, por favor ve a la ciudad: ',
	BBTEXT:'versión texto',
	BBHTML:'versión tabla',
	MSG413ERR:'<h3>El informe generado es demasiado largo.</h3><p>Use las opciones disponibles y reduzcalo para publicar sin problemas.</p>',
	CHKREPORTFORMAT:'Generar informes usando tablas',
	WALLNOTSAVED:'La muralla no está guardada',
	WALLSAVED:'Muralla guardada',
	POPSELRECRUNIT:'click, para seleccionar la unidad de producción por defecto',
	POPRECRUNITTRADE:'click, para rellenar los recursos necesarios para reclutar la unidad seleccionada',
	POPINSERTLASTREPORT:'Pegar el último informe convertido',
	MSGCOPYREPORT:'El informe ha sido guardado. Por favor click [paste_icon] on el foro o la ventana de nuevo mensaje para pegarlo',
	POPDISABLEALARM:'Desconectar alarma',
	SOUNDSETTINGS:'Ajustes de sonido',
	CHKSOUNDMUTE:'Silenciar',
	SOUNDVOLUME:'Volumen',
	SOUNDURL:'URL fichero sonido',
	CHKSOUNDLOOP:'Repetir',
	POPSOUNDLOOP:'Reproducción continua',
	POPSOUNDMUTE:'Desactivar sonido',
	POPSOUNDPLAY:'Reproducir con los ajustes actuales',
	POPSOUNDSTOP:'Detener reproducción',
	POPSOUNDURL:'Ruta URL al fichero de sonido',
	ABH:{
		WND:{
			UNITFRAME:'elija su unidad',
			WINDOWTITLE:'Ayudante del constructor de ejercitos',
			DESCRIPTION1:'En esta ciudad, tienes [population] población libre',
			DESCRIPTION2:'Que es suficiente para hacer [max_units]',
			DESCRIPTION3:'Tú [yesno] tienes [research] investigado.',
			DESCRIPTION4:'Puedes agregar un máximo de [max_queue] unidades',
			TARGET:'elige tu edificio objetivo',
			PACKAGE:'paquete de recursos por envío (unidades)',
			BTNSAVE:'guardar ajustes',
			TOOLTIPOK:'click, para seleccionar la unidad por defecto para la que enviarás recursos',
			TOOLTIPNOTOK:'unidad no investigada',
			HASRESEARCH:'HAZ',
			NORESEARCH:'NO HAGAS',
			SETTINGSAVED:'Los ajustes para [city] guardados',
		},
		RESWND:{
			RESLEFT:'recursos pendientes de envío',
			IMGTOOLTIP:'click, para rellenar recursos',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Disponible nueva versión',
		INSTALL:'Instalar',
		REMINDER:'Recordármelo más tarde',
		REQRELOAD:'Se necesita cargar de nuevo el sitio',
		RELOAD:'Cargar de nuevo',
	},
	LANGS:{
		LANG:'Traducción para idioma:',
		SEND:'Enviar a publicar',
		SAVE:'Guardar y probar',
		RESET:'Restablecer el idioma por defecto',
		REMOVE:'¿Borrar tu traducción?',
	},
	HELPTAB5:'Traducción',
	MSGRTSHOW:'Información de la revuelta en curso',
	MSGRTCSTIME:'Horario CS',
	MSGRTONL:'¿conectado?',
	BTNSIMUL:'Simulador',
	EMOTS:{
		LABEL:'¿Quieres más emoticonos?',
		MESS:'Pega enlaces de un emoticono, cada uno en una nueva línea',
	},
	COMMAND:{
		ALL:'Todo',
		INCOMING:'entrante',
		OUTGOING:'saliente',
		RETURNING:'retornando',
		FORTOWN:'ciudad:',
	},
	LASTUPDATE:'1487465086352',
	CHKWONDERTRADE:'Al enviar recursos para las maravillas del mundo, enviar cantidades máximas iguales',
	MOBILEVERSION:'versión movil',
	AO:{
		TITLE:'Visión general de la Academia',
	},
	CHKOLDTRADE:'Utilizar el diseño del comercio antiguo',
	TSL:{
		WND:{
			TOOLTIP:'ver las ciudades clasificadas',
			WINDOWTITLE:'Lista de ciudades clasificadas',
		},
	},
	QUESTION:'Pregunta',
	WALL:{
		WANTDELETECURRENT:'¿Quiere borrar el estado actual de la muralla?',
		DELETECURRENT:'Borrar el siguiente dato',
		LISTSTATE:'Condición de la muralla el dia',
		LISTSAVED:'Muralla salvada el dia',
	},
	RADAR:{
		ALL:'Cualquier ciudad',
		BTNSAVEDEFAULT:'Guardar valores como predeterminados',
		TOWNPOINTS:'Puntos mínimos de la ciudad',
		TOWNRESERVED:'Reserva',
		TOWNOWNER:'Propietario',
		CSTIME:'Tiempo CS',
		TOWNNAME:'Ciudad',
		BTNFIND:'Buscar',
		MAXCSTIME:'Tiempo máximo del colono',
		FIND:'Buscar',
		TOWNFINDER:'Buscar ciudades',
	},
	POPSOUNDEG:'Ejemplo: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	MSGSHOWCOST:'Coste de unidades perdidas',
	BTNVIEWBB:'Código BB',
}