RepConvLangArray.pl = {
	AUTHOR:'Potusek',
	BTNCONV:'Konwertuj',
	BTNGENER:'Generuj',
	BTNSRC:'Źródło',
	BTNVIEW:'Podgląd',
	BTNSAVE:'Zapisz',
	BTNMARKS:'Oznacz jako przeczytane',
	BTNMARKA:'Oznacz wszystkie jako przeczytane',
	MSGTITLE:'Opcje konwersji',
	MSGQUEST:'Które z danych chcesz opublikować?',
	MSGALL:'Wszystkie',
	MSGBBCODE:'Po opublikowaniu raportu, możesz powiązać go z wiadomościami lub forum korzystając z BBCode.',
	MSGRESOURCE:'Łup',
	MSGUNITS:'Jednostki',
	MSGBUILD:'Budynki',
	MSGUSC:'Wykorzystane srebrne monety',
	MSGRAW:'Surowce',
	MSGSHOWCOST:'Koszty utraconych jednostek',
	SUPPORT:'Wspiera',
	SPY:'Szpieguje',
	CONQUER:'Podbił',
	LOSSES:'Straty',
	HIDDEN:'Ukryte',
	NOTUNIT:'[i]Brak[/i]',
	TOWN:'[i]Miasto:[/i] ',
	PLAYER:'[i]Gracz:[/i] ',
	ALLY:'[i]Sojusz:[/i] ',
	CAST:'rzucił:',
	ONTOWER:'Na miasto:',
	MSGHIDAD:'Ukrywanie miasta',
	MSGFORUM:'Raport będzie publikowany',
	BBALLY:'forum sojuszu / w wiadomości',
	BBFORUM:'forum zewnętrzne',
	ERRGETSRC:'Wystąpił błąd! Proszę wygenerować źródło i wysłać jako załącznik na adres potusek@westtax.info',
	ICOCLOSE:'Zamknij',
	ICOHELP:'O konwerterze',
	MSGPREVIEW:'<b>Podgląd raportu</b>',
	HELPTAB1:'O konwerterze',
	HELPTAB2:'Jak to działa',
	HELPTAB3:'Zmiany',
	HELPTAB4:'Ustawienia',
	HLPVERSION:'Wersja',
	HLPFIXED:'Poprawiono',
	HLPADDED:'Dodano',
	MSGHUMAN:{
		OK:'Informacje zostały zapisane',
		ERROR:'Wystąpił błąd podczas zapisu',
		YOUTUBEERROR: 'Niepoprawny link lub niedozwolone odtwarzanie poza youtube',
	},
	STATSPOINT:'Punkty',
	STATSRANK:'Ranking',
	LABELS:{
		attack:{
			ATTACKER:'Agresor',
			DEFENDER:'Obrońca',
			MSGHIDAT:'atakującego',
			MSGHIDDE:'obrońcy',
			MSGATTUNIT:'Wojska atakującego',
			MSGDEFUNIT:'Wojska obrońcy',
		},
		support:{
			ATTACKER:'Wspierający',
			DEFENDER:'Wspierany',
			MSGHIDAT:'wspierającego',
			MSGHIDDE:'wspieranego',
			MSGATTUNIT:'Wojska wspierającego',
			MSGDEFUNIT:'Wojska obrońcy',
		},
		espionage:{
			ATTACKER:'Szpiegujący',
			DEFENDER:'Szpiegowany',
			MSGHIDAT:'szpiegującego',
			MSGHIDDE:'szpiegowanego',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'szczegóły polecenia',
	MSGRETURN:'(powrót)',
	MSGCLAIM:'rezerwuje miasto',
	MSGCLAIMPPUP:'Generuj rezerwację',
	MSGGENBBCODE:'Generuj listę w BBCode',
	MSGDEFSITE:'Pokonane...',
	MSGLOSSITE:'Stracone...',
	MSGASATT:'...w roli atakującego',
	MSGASDEF:'...w roli obrońcy',
	MSGDIFF1:'nie pokazuj różnic',
	MSGDIFF2:'pokaż różnice',
	MSGDIFF3:'pokaż tylko różnice',
	BBCODELIMIT:'W związku z ograniczeniem ilości tekstu w jednym poście, w przypadku długiej listy, dane zostały podzielone na grupy. Każdą grupę wklejaj jako osobny wpis.',
	CHKPOWERNAME:'Wyświetlaj czas, jaki pozostał do możliwości użycia czaru',
	CHKNIGHTNAME:'Zaciemniaj polis w bonusie nocnym',
	CHKFORUMTABS:'Zamień przewijane zakładki na forum, na wieloliniowe',
	BTNRESERVE:'Rezerwacja',
	LNKRESERVE:'Rezerwacje',
	LBLGETRESER:'Pobieranie danych ...',
	BTNCHECK:'Sprawdzenie rezerwacji',
	CHKCMDIMG:'Pokaż ikony rozkazów przy docelowym mieście',
	STATSLINK:'Statystyki wyświetlaj ze strony',
	BTNSUPPLAYERS:'Lista graczy',
	CHKUNITSCOST:'Na raporcie pokazuj koszt straconych jednostek',
	CHKOCEANNUMBER:'Wyświetlaj numery mórz',
	MSGRTLBL:'Informacja o buncie',
	MSGRTSHOW:'Dołącz do raportu informacje o buncie',
	MSGRTONLINE:'Czy będziesz online podczas buntu?',
	MSGRTYES:'Tak',
	MSGRTNO:'Nie',
	MSGRTGOD:'Bóg',
	MSGRTCSTIME:'CK',
	MSGRTONL:'online?',
	MSGRTERR:'Znajdujesz się w niewłaściwym mieście!<br/>Aby wygenerować informacje o buncie, przejdź do miasta: ',
	BBTEXT:'wersja tekstowa',
	BBHTML:'wersja oparta na tabelach',
	BBIMG:'jako pojedynczy obraz',
	MSG413ERR:'<h3>Jeżeli przez dłuższą chwilę widzisz ten napis, wówczas wygenerowany raport jest zbyt obszerny.</h3><p>Użyj dostępnych opcji redukując ilość publikowanych danych.</p>',
	CHKREPORTFORMAT:'Generowanie raportów w oparciu o tabele',
	WALLNOTSAVED:'Mur nie został zapisany',
	WALLSAVED:'Mur jest zapisany',
	POPSELRECRUNIT:'kliknij, aby wybrać domyślną jednostkę do produkcji',
	POPRECRUNITTRADE:'kliknij, żeby zapełnić handlarza surowcami dla wybranej jednostki',
	POPINSERTLASTREPORT:'Wstaw ostatni wynik konwersji',
	MSGCOPYREPORT:'Wynik konwersji został zapisany. Proszę kliknąć [paste_icon] na forum lub w wiadomości, aby wstawić',
	POPDISABLEALARM:'Wyłącz alarm',
	SOUNDSETTINGS:'Ustawienia dźwięku',
	CHKSOUNDMUTE:'Wycisz',
	SOUNDVOLUME:'Głośność',
	SOUNDURL:'Ścieżka do pliku',
	CHKSOUNDLOOP:'odtwarzaj w pętli',
	POPSOUNDLOOP:'odtwarzaj w pętli',
	POPSOUNDMUTE:'Wycisz dźwięk',
	POPSOUNDPLAY:'Odtwórz z bieżącymi ustawieniami',
	POPSOUNDSTOP:'Przerwij odtwarzanie',
	POPSOUNDURL:'Ścieżka do pliku z dźwiękiem',
	POPSOUNDEG:'np: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	STATS:{
		PLAYER:'Statystyki gracza',
		ALLY:'Statystyki sojuszu',
		TOWN:'Statystyki miasta',
        INACTIVE:'Nieaktywny',
        CHKINACTIVE : 'Pokaż nieaktywność graczy',
		INACTIVEDESC : 'W tym czasie nie odnotowano punktów walki jak i rozbudowy',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Pomocnik w budowaniu armii',
			UNITFRAME:'Wybierz domyślną jednostkę',
			DESCRIPTION1:'W obecnym mieście masz [population] wolnych mieszkańców',
			DESCRIPTION2:'Co wystarczy do zbudowania: [max_units]',
			DESCRIPTION3:'[yesno] badanie [research]',
			DESCRIPTION4:'Możesz zakolejkować max [max_queue] jednostek',
			TARGET:'wybierz ile zbudować',
			PACKAGE:'na ile jednostek domyślnie wysyłać',
			BTNSAVE:'zapisz ustawienia',
			TOOLTIPOK:'kliknij, aby wybrać jednostkę dla której chcesz domyślnie wysyłać surowce',
			TOOLTIPNOTOK:'jednostka nie została zbadana',
			HASRESEARCH:'MASZ',
			NORESEARCH:'NIE MASZ',
			SETTINGSAVED:'Ustawienia dla miasta [city] zostały zapisane',
		},
		RESWND:{
			RESLEFT:'pozostało do wysłania',
			IMGTOOLTIP:'kliknij, żeby wypełnić pola surowców',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Dostępna nowa wersja',
		INSTALL:'Zainstaluj',
		REMINDER:'Przypomnij później',
		REQRELOAD:'Wymagane odświeżenie strony',
		RELOAD:'Odśwież',
	},
	HELPTAB5:'Tłumaczenie',
	LANGS:{
		REMOVE:'Skasować Twoje tłumaczenie?',
		RESET:'Przywróć domyślny język',
		SAVE:'Zapisz i testuj',
		SEND:'Wyślij do publikacji',
		LANG:'Tłumaczenie dla języka:'
	},
    BTNSIMUL: 'Symulator',
    EMOTS : {
        LABEL: 'Chcesz więcej emotek?',
        MESS: 'Wklej linki do obrazków, każdy w nowej linii'
    },
    COMMAND : {
        ALL: "Wszystkie",
        INCOMING: "nadchodzące",
        OUTGOING: "wychodzące",
        RETURNING: "powracające",
        FORTOWN : "miasto:"
    },
    RADAR :{
        TOWNFINDER: "Wyszukiwanie miast",
        FIND: "Szukane",
        MAXCSTIME:"Maksymalny czas statku kolonizacyjnego",
        MAXUNITTIME:"Maksymalny czas",
        BTNFIND: "Szukaj",
        TOWNNAME: "Miasto",
        CSTIME: "Czas",
        UNITTIME: "Czas",
        TOWNOWNER: "Właściciel",
        TOWNRESERVED: "Rezerwacja",
        TOWNPOINTS: "Minimalne punkty miasta",
        BTNSAVEDEFAULT: "Zapisz wartości jako domyślne",
		ALL: "Dowolne miasto",
		SHOWCITIES: "Pokaż miasta"
    },
    WALL : {
        LISTSAVED : 'Zapis muru na dzień',
        LISTSTATE : 'Stan muru na dzień',
        DELETECURRENT : 'Usuń bieżący zapis',
        WANTDELETECURRENT : 'Czy chcesz usunąć bieżący zapis muru?'
    },
    QUESTION : 'Pytanie',
	TSL:{
    	WND:{
    		WINDOWTITLE:'Lista posortowanych miast',
    		TOOLTIP:'pokaż posortowane miasta'
    	}
    },
    CHKOLDTRADE : 'Używaj starego układu handlu',
    AO:{
		TITLE: 'Przegląd Akademii'
    },
	MOBILEVERSION: 'Wersja mobilna',
	CHKWONDERTRADE : 'Podczas wysyłania zasobów do cudów świata, wyślij maksymalne równe ilości',
    CHKTOWNPOPUP : 'Wyświetlaj dymek z informacją o wojsku po najechaniu na nazwę miasta w rozwijanej liście miast',
    POPWONDERSHOT : 'Ilość dostępnych przyspieszeń budowy',
    CHKTACL : 'Włącz przesuwanie listy ruchu wojsk',
    BTNCOMPARE : 'Pakt vs Wróg',
    ALLYCOMPARETITLE: 'Porównanie sojuszy koalicji z wrogimi sojuszami',
    CHKMCOL : 'Przypisz kolory wiadomościom zgodnie z ustalonym schematem kolorowania',
    CHKBUPO : 'Pokaż punkty rozbudowy',
    CHKMOUSEWHEELZOOMBULLEYE: 'Użyj kółka myszy do zmiany przybliżenia mapy',
    POPINSERTEMOT: 'Wstaw emotikonę',
    CHKIMGBTN: 'Wyświetlaj ośmiornicę na przyciskach GRCRTools'
}