RepConvLangArray.hu = {
	AUTHOR:'LegatuS, Phrometheus, Skyes, Vesztettem, alugev, Bud.Spencer, DOBss, Nagyhús',
	BTNCONV:'Átalakítás',
	BTNGENER:'Generálás',
	BTNVIEW:'Előlnézet',
	BTNSAVE:'Mentés',
	MSGTITLE:'Jelentés átalakítása',
	MSGQUEST:'Melyik adatokat szeretné közzétenni?',
	MSGBBCODE:'A jelentés közzététele után BB-kód segítségével beilleszthető lesz a fórumok és üzenetekben.',
	MSGRESOURCE:'Zsákmány',
	MSGUNITS:'Egységek',
	MSGBUILD:'Épületek',
	MSGUSC:'Felhasznált ezüstpénzek',
	MSGRAW:'Nyersanyagok',
	SUPPORT:'Támogatás',
	SPY:'Kémkedés',
	CONQUER:'Meghódított',
	LOSSES:'Veszteségek',
	HIDDEN:'Nem látható.',
	NOTUNIT:'[i]Nincs[/i]',
	TOWN:'[i]Város:[/i] ',
	PLAYER:'[i]Játékos:[/i] ',
	ALLY:'[i]Szövetség:[/i] ',
	CAST:'elfoglalás:',
	ONTOWER:'Városon:',
	MSGHIDAD:'Városok elrejtése',
	MSGFORUM:'A jelentés közzétételre kerül',
	BBALLY:'szövetségi fórumok / üzenetben',
	BBFORUM:'külső fórum',
	ICOCLOSE:'Bezár',
	ICOHELP:'Az átalakítóról',
	MSGPREVIEW:'<b>Jelentés előnézete</b>',
	HELPTAB1:'A bővítményről',
	HELPTAB2:'Hogyan működik',
	HELPTAB3:'Változtatási napló',
	HELPTAB4:'Beállítások',
	MSGHUMAN:{
		OK:'Az adatok mentése megtörtént',
		ERROR:'Hiba történt',
		YOUTUBEERROR:'Hibás link vagy nem lejátszható youtube-on kívül',
	},
	LABELS:{
		attack:{
			ATTACKER:'Támadó',
			DEFENDER:'Védő',
			MSGHIDAT:'támadó',
			MSGHIDDE:'védő',
			MSGATTUNIT:'Támadó egységek',
			MSGDEFUNIT:'Védő egységek',
		},
		support:{
			ATTACKER:'Támogató',
			DEFENDER:'Támogatott',
			MSGHIDAT:'támogató',
			MSGHIDDE:'támogatott',
			MSGATTUNIT:'Támogató egységek',
			MSGDEFUNIT:'Védő egységek',
		},
		espionage:{
			ATTACKER:'Kémkedő',
			DEFENDER:'Kémkedett',
			MSGHIDAT:'kémdedő',
			MSGHIDDE:'kémkedett',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'parancsok részletei',
	MSGRETURN:'(visszatérő)',
	MSGGENBBCODE:'BB-kód lista generálása',
	MSGDEFSITE:'Legyőzöttek...',
	MSGLOSSITE:'Veszteségek...',
	MSGASATT:'...támadóként',
	MSGASDEF:'...védőként',
	MSGDIFF1:'különbségek elrejtése ',
	MSGDIFF2:'különbségek mutatása',
	MSGDIFF3:'csak a különbségek mutatása',
	BBCODELIMIT:'Mivel a hozzászólásokban csak limitált számú karaktert lehet használni, így a hosszabb listák csoportkra lettek osztva. Minden csoportot külön hozzászólásban célszerű beilleszteni.',
	CHKPOWERNAME:'Az isteni erő újbóli használatához hátralévő idő mutatása',
	CHKFORUMTABS:'A fórumon több sor megjelnítése a vízszintes görgetés helyett',
	STATSLINK:'Statisztikák forrása',
	BTNSUPPLAYERS:'Játékosok listája',
	CHKUNITSCOST:'Az elesett egységek árának megjelenítése',
	CHKOCEANNUMBER:'Tenger számának megjelenítése',
	MSGRTLBL:'Lázadással kapcsolatos információk',
	MSGRTSHOW:'Lázadással kapcsolatos információk megjelenítése',
	MSGRTONLINE:'Aktív lesz a lázadás folyamán?',
	MSGRTYES:'Igen',
	MSGRTNO:'Nem',
	MSGRTGOD:'Isten',
	MSGRTCSTIME:'GYH idő',
	MSGRTONL:'aktív?',
	MSGRTERR:'Rossz városban vagy!<br/>Lázadási információkhoz menj ebbe a városba ',
	BBTEXT:'szöveges verzió',
	BBHTML:'táblázatos verzió',
	MSG413ERR:'<h3>Az átalakított jelentés túl nagy.</h3><p>Használja a rendelkezésre álló opciókat, hogy csökkentse a méretet.</p>',
	CHKREPORTFORMAT:'Jelentések átalakítása táblázatok használatával',
	WALLNOTSAVED:'A fal nincs mentve',
	WALLSAVED:'A fal mentve',
	POPSELRECRUNIT:'kattints az alapértelmezett termelőegység kiválasztásához',
	POPRECRUNITTRADE:'kattintson a szükséges nyersanyag beillesztéséhez a kiválasztott egységhez',
	POPINSERTLASTREPORT:'Az utolsó átalakított jelentés beillesztése',
	MSGCOPYREPORT:'A jelentés el lett mentve. Kérjük, a beillesztéshez kattintson a [paste_icon] ikonra a fórumokon vagy üzenet írásánál.',
	POPDISABLEALARM:'Támadásjelző kikapcsolása',
	SOUNDSETTINGS:'Hang beállítások',
	CHKSOUNDMUTE:'Némítás',
	SOUNDVOLUME:'Hangerő',
	SOUNDURL:'Hangfájl url címe',
	CHKSOUNDLOOP:'ismétlés',
	POPSOUNDLOOP:'Lejátszás ismétléssel',
	POPSOUNDMUTE:'Hang némítása',
	POPSOUNDPLAY:'Lejátszás jelenlegi beállításokkal',
	POPSOUNDSTOP:'Lejátszás megállítása',
	POPSOUNDURL:'A hangfájlhoz vezető url cím',
	STATS:{
		PLAYER:'Játékos statisztikája',
		ALLY:'Szövetség statisztikák',
		TOWN:'Város statisztikák',
		INACTIVEDESC:'Ennyi idelye nem növekedett a játékos pontszáma vagy nem szerzett harci pontot',
		CHKINACTIVE:'Inaktív játékosok mutatása',
		INACTIVE:'Inaktív',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Sereg Építés Segítő',
			UNITFRAME:'válassza ki az egységet',
			DESCRIPTION1:'Ebben a városba [population] szabad népessége van',
			DESCRIPTION2:'Amely elég [max_units] egység készítésére',
			DESCRIPTION3:'Már kifejlesztetted a(z) [research] fejlesztést: [yesno]',
			DESCRIPTION4:'A kiképzési sorrendbe maximum [max_queue] egység fél el',
			TARGET:'válassza ki a kívánt mennyiséget (egység)',
			PACKAGE:'nyersanyag/szállítmány (egység)',
			BTNSAVE:'beállítások mentése',
			TOOLTIPOK:'kattintson az egység kiválasztásához, amelyre majd szeretne nyersanyagokat küldeni',
			TOOLTIPNOTOK:'az egység nincs kifejlesztve',
			HASRESEARCH:'TEDD',
			NORESEARCH:'NINCS',
			SETTINGSAVED:'A beállítások [city] városára sikeresen mentve',
		},
		RESWND:{
			RESLEFT:'szükséges nyersanyagok',
			IMGTOOLTIP:'kattintson a szükséges nyersanyag beillesztéséhez',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Új verzió elérhető',
		INSTALL:'Telepítés',
		REMINDER:'Emlékeztess később',
		REQRELOAD:'Frissítés szükséges',
		RELOAD:'Frissítés',
	},
	LANGS:{
		LANG:'Fordítás:',
		SEND:'Elküldés közzététele',
		SAVE:'Mentés',
		RESET:'Alapértelmezett nyelv visszaállítása',
		REMOVE:'Törölni szeretné a fordítás?',
	},
	HELPTAB5:'Fordítás',
	BTNSIMUL:'Szimulátor',
	EMOTS:{
		LABEL:'Szeretne több hangulatjelet?',
		MESS:'Illessze be a linket a hangulatjelhez, mindegyiket külön sorra',
	},
	COMMAND:{
		ALL:'Mind',
		INCOMING:'bejövő',
		OUTGOING:'kimenő',
		RETURNING:'visszatérő',
		FORTOWN:'város:',
	},
	BTNVIEWBB:'BB-kód',
	MSGSHOWCOST:'Az elvesztett egységek ára',
	CHKWONDERTRADE:'A világcsodákra maximális nyersanyagok küldendők',
	MOBILEVERSION:'Mobil verzió',
	AO:{
		TITLE:'Akadémia áttekintő',
	},
	CHKOLDTRADE:'A régi kereskedelmi elrendezés használata',
	TSL:{
		WND:{
			WINDOWTITLE:'Közeli városok',
			TOOLTIP:'közeli városok mutatása',
		},
	},
	QUESTION:'Kérdés',
	WALL:{
		WANTDELETECURRENT:'Biztosan törölni szeretné a kiválasztott mentést?',
		DELETECURRENT:'A kiválasztott mentés törlése',
		LISTSTATE:'Városfal állapota ekkor',
		LISTSAVED:'Városfal mentése ekkorról',
	},
	RADAR:{
		ALL:'Bármilyen város',
		TOWNPOINTS:'Minimális pontszám',
		BTNSAVEDEFAULT:'Értékek mentése alapértelmezettként',
		TOWNRESERVED:'Fenntartás',
		TOWNOWNER:'Tulajdonos',
		CSTIME:'GYH idő',
		TOWNNAME:'Város',
		BTNFIND:'Keresés',
		MAXCSTIME:'Maximális gyarmatosítóhajó idő',
		FIND:'Keresés',
		TOWNFINDER:'Város kereső',
	},
	POPSOUNDEG:'például: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	BBIMG:'egyetlen kép',
	LASTUPDATE:'1487468651957',
}