RepConvLangArray.it = {
	INFO:{
		0:'Potusek',
		1:'grepolis@potusek.eu',
	},
	WEBSITE:'Sito web',
	AUTHOR:'av250866@gmail.com, G.O.W., Marco305, Xyarghas, TeseoN86, ander26',
	BTNCONV:'Converti',
	BTNGENER:'Crea',
	BTNSRC:'Sorgente',
	BTNVIEW:'Anterprima',
	BTNSAVE:'Salva',
	BTNMARKS:'Segna come letto',
	BTNMARKA:'Segna tutto come letto',
	MSGTITLE:'Converti il report',
	MSGQUEST:'Quali informazioni vuoi pubblicare?',
	MSGALL:'Tutto',
	MSGBBCODE:'Una volta pubblicato il report, potrai inserirlo nelle news o nel forums tramite il BBCode.',
	MSGRESOURCE:'Bottino',
	MSGUNITS:'Unità',
	MSGBUILD:'Edifici',
	MSGUSC:'Argento impiegato',
	MSGRAW:'Materiali',
	SUPPORT:'Supporti',
	SPY:'Spiando',
	CONQUER:'Conquistata',
	LOSSES:'Persa',
	HIDDEN:'Nascosto',
	NOTUNIT:'[i]Nessuna[/i]',
	TOWN:'[i]Città:[/i] ',
	PLAYER:'[i]Giocatore:[/i] ',
	ALLY:'[i]Alleanza:[/i] ',
	CAST:'lancia:',
	ONTOWER:'sulla città:',
	MSGHIDAD:'Nascondi città',
	MSGFORUM:'Il report sarà pubblicato',
	BBALLY:'Forum alleanza / nel messaggio',
	BBFORUM:'forum esterno',
	ERRGETSRC:'Errore! Per favore, creare il sorgente ed inviarlo come allegato a potusek@westtax.info',
	ICOCLOSE:'Chiudi',
	ICOHELP:'Riguardo al converter',
	MSGPREVIEW:'<b>Anteprima report</b>',
	HELPTAB1:'Riguardo a',
	HELPTAB2:'Come funziona',
	HELPTAB3:'Cambiamenti',
	HELPTAB4:'Opzioni',
	HLPVERSION:'Versione',
	HLPFIXED:'Corretto',
	HLPADDED:'Aggiunto',
	MSGHUMAN:{
		OK:'La informazione è stata salvata',
		ERROR:'è avvenuto un errore in scrittura',
		YOUTUBEERROR:'collegamento errato o non ha permesso di giocare fuori youtube',
	},
	STATSPOINT:'Punti',
	STATSRANK:'classifica',
	LABELS:{
		attack:{
			ATTACKER:'Attaccante',
			DEFENDER:'Difensore',
			MSGHIDAT:'attaccante',
			MSGHIDDE:'difensore',
			MSGATTUNIT:'Esercito attaccante',
			MSGDEFUNIT:'Esercito difensore',
		},
		support:{
			ATTACKER:'In supporto',
			DEFENDER:'Supportato',
			MSGHIDAT:'in supporto',
			MSGHIDDE:'supportato',
			MSGATTUNIT:'Esercito in supporto',
			MSGDEFUNIT:'Esercito difensore',
		},
		espionage:{
			ATTACKER:'Spia',
			DEFENDER:'Spiato',
			MSGHIDAT:'spia',
			MSGHIDDE:'spiato',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'dettagli ordine',
	MSGRETURN:'(ritorno)',
	MSGCLAIM:'città prenotata',
	MSGCLAIMPPUP:'Genera prenotazione',
	MSGGENBBCODE:'Genera una lista in BBCode',
	MSGDEFSITE:'Sconfitto...',
	MSGLOSSITE:'Perdite...',
	MSGASATT:'...come attaccante',
	MSGASDEF:'...come difensore',
	MSGDIFF1:'non mostrare le differenze',
	MSGDIFF2:'mostra le differenze',
	MSGDIFF3:'mostra solo le differenze',
	BBCODELIMIT:'A causa della quantità di testo limitata in un singolo post, in caso di liste molto lunghe i dati saranno divisi in gruppi. Copiare ciascun gruppo come post separato.',
	CHKPOWERNAME:'Mostra il tempo mancante all\'utilizzo di un nuovo incantesimo',
	CHKNIGHTNAME:'Rende buie le città in bonus notturno',
	CHKFORUMTABS:'Sostituisce le tabelle a scorrimento nel forum con multilinea',
	HELPTAB5:'Traduzione',
	CHKCMDIMG:'Visualizza la icona per la citta di destinazione dei comandi',
	STATSLINK:'Statistiche da display',
	BTNSUPPLAYERS:'Lista dei giocatori',
	CHKUNITSCOST:'Il report mostra il costo delle unità perse',
	CHKOCEANNUMBER:'Visualizza il numero dei mari',
	MSGRTLBL:'Informazioni rivolta',
	MSGRTSHOW:'Aggiungi informazioni rivolta in corso',
	MSGRTONLINE:'Sarai connesso durante la rivolta rossa?',
	MSGRTYES:'Si',
	MSGRTNO:'No',
	MSGRTGOD:'Dio',
	MSGRTCSTIME:'Tempo CS',
	MSGRTONL:'connesso?',
	MSGRTERR:'Sei nella città sbagliata!<br/>Per creare un rapporto della rivolta, vai alla città: ',
	BBTEXT:'versione testo',
	BBHTML:'versione tabelle',
	MSG413ERR:'<h3>Il rapporto generato è troppo grande.</h3><p>Usa le opzioni disponibili e riducilo per pubblicarlo senza problemi.</p>',
	CHKREPORTFORMAT:'Genera il rapporto usando le tabelle',
	WALLNOTSAVED:'Wall non è stato salvato',
	WALLSAVED:'Wall è stato salvato',
	POPSELRECRUNIT:'clicca, per selezionare le unità da produrre di default',
	POPRECRUNITTRADE:'clicca, per riempire con le risorse necessarie a reclutare le unità selezionate',
	POPINSERTLASTREPORT:'Incolla l ultimo rapporto creato',
	MSGCOPYREPORT:'Il rapporto è stato salvato. Per favore clicca [paste_icon] nel forum o nel nuovo messaggio per incollarlo',
	POPDISABLEALARM:'Disabilita allarme',
	SOUNDSETTINGS:'Opzioni suono',
	CHKSOUNDMUTE:'Silenzioso',
	SOUNDVOLUME:'volume',
	SOUNDURL:'url del file sonoro',
	CHKSOUNDLOOP:'ripeti',
	POPSOUNDLOOP:'Suona a ripetizione',
	POPSOUNDMUTE:'Silenzia il suono',
	POPSOUNDPLAY:'Suona con le opzioni correnti',
	POPSOUNDSTOP:'Smetti di suonare',
	POPSOUNDURL:'Percorso al file sonoro',
	STATS:{
		PLAYER:'Statistiche giocatore',
		ALLY:'Statistiche alleanza',
		TOWN:'Statistiche città',
		INACTIVE:'Inattivo',
		CHKINACTIVE:'Mostra i giocatori inattivi',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Aiuto costruzione esercito',
			UNITFRAME:'scegli le tue unità',
			DESCRIPTION1:'In questa città, la popolazione libera è: [population]',
			DESCRIPTION2:'Che è sufficiente per creare [max_units] unità',
			DESCRIPTION3:'Hai [yesno] una [research] ricercata.',
			DESCRIPTION4:'Puoi mettere in coda fino a [max_queue] unità',
			TARGET:'Scegli le unità da costruire',
			PACKAGE:'Risorse sufficienti per creare(unità)',
			BTNSAVE:'salva opzioni',
			TOOLTIPOK:'clicca, per selezionare la unità standard per la quale manderai risorse',
			TOOLTIPNOTOK:'questa unità non è ancora stata ricercata',
			HASRESEARCH:'',
			NORESEARCH:'NON',
			SETTINGSAVED:'Le opzioni per la città [city] sono state salvate',
		},
		RESWND:{
			RESLEFT:'risorse rimaste da inviare',
			IMGTOOLTIP:'clicca, per caricare le risorse',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Nuova versione disponibile',
		INSTALL:'Installa',
		REMINDER:'Ricordamelo più tardi',
		REQRELOAD:'E\' necessario aggiornare la pagina',
		RELOAD:'Aggiorna',
	},
	LANGS:{
		LANG:'Traduzione per la lingua: ',
		SEND:'Invia per la pubblicazione',
		SAVE:'Salva e prova',
		RESET:'Ripristina la lingua predefinita',
		REMOVE:'Cancellare la tua traduzione?',
	},
	BTNSIMUL:'Simulatore',
	EMOTS:{
		LABEL:'Vuoi altre faccine?',
		MESS:'Copia i links alle faccinen, uno solo per riga',
	},
	COMMAND:{
		ALL:'Tutto',
		INCOMING:'in arrivo',
		OUTGOING:'in partenza',
		RETURNING:'di ritorno',
		FORTOWN:'città:',
	},
	MSGSHOWCOST:'costo delle unità perse',
	BBIMG:'immagine singola',
	RADAR:{
		FIND:'Cerca',
		MAXCSTIME:'Tempo massimo coloniale',
		TOWNFINDER:'Cerca città',
		BTNFIND:'Cerca',
		TOWNNAME:'Città',
		TOWNOWNER:'Proprio',
		TOWNRESERVED:'Prenotazione',
		TOWNPOINTS:'Punti minimi Città',
		BTNSAVEDEFAULT:'Salva come valore di default',
		ALL:'Tutte le città',
	},
	LASTUPDATE:'1488490709268',
}