RepConvLangArray.tr = {
	AUTHOR:'Lazmanya 61, zabidin, irfanirfan',
	BTNCONV:'Dönüştür',
	BTNGENER:'Oluştur',
	BTNVIEW:'Önizle',
	BTNSAVE:'Kaydet',
	MSGTITLE:'Raporu dönüştür',
	MSGQUEST:'Hangi içerikler gösterilebilir?',
	MSGBBCODE:'Bu raporu yayınlandıktan sonra BB kodunu kullanarak mesajlara ya da foruma dahil edebilirsin.',
	MSGRESOURCE:'Ganimet',
	MSGUNITS:'Birimler',
	MSGBUILD:'Binalar',
	MSGUSC:'Kullanılan gümüş paralar',
	MSGRAW:'Hammaddeler',
	SUPPORT:'Yardım',
	SPY:'Casusluk',
	CONQUER:'Fethetmek',
	LOSSES:'Kayıplar',
	HIDDEN:'Gizlendi',
	NOTUNIT:'[i]Hiçbiri[/i]',
	TOWN:'[i]Şehir:[/i] ',
	PLAYER:'[i]Oyuncu:[/i] ',
	ALLY:'[i]Müttefik:[/i] ',
	CAST:'Yapım:',
	ONTOWER:'Şehirde:',
	MSGHIDAD:'şehirleri gizle',
	MSGFORUM:'Raporu yayınla',
	BBALLY:'ittifak forumda ve mesajlarda',
	BBFORUM:'diğer forumlarda',
	ICOCLOSE:'Kapat',
	ICOHELP:'Dönüştürücü hakkında',
	MSGPREVIEW:'<b>Raporu önizleme</b>',
	HELPTAB1:'Hakkında',
	HELPTAB2:'Nasıl Çalışır',
	HELPTAB3:'Değişiklikler',
	HELPTAB4:'Ayarlar',
	MSGHUMAN:{
		OK:'Kaydedildi',
		ERROR:'Yazarken bir hata oluştu',
		YOUTUBEERROR:'Geçersiz bağlantı adresi veya youtube dışında oynatılamaz',
	},
	LABELS:{
		attack:{
			ATTACKER:'Saldırı',
			DEFENDER:'Destek',
			MSGHIDAT:'saldırgan',
			MSGHIDDE:'savunmacı',
			MSGATTUNIT:'Saldırganın birlikleri',
			MSGDEFUNIT:'Savunmacının birlikleri',
		},
		support:{
			ATTACKER:'Destekleyen',
			DEFENDER:'Desteklenen',
			MSGHIDAT:'destekleyen',
			MSGHIDDE:'desteklenen',
			MSGATTUNIT:'destekleyen birim',
			MSGDEFUNIT:'Savunma birimleri',
		},
		espionage:{
			ATTACKER:'Casus',
			DEFENDER:'Casusluk',
			MSGHIDAT:'casuslayan',
			MSGHIDDE:'casuslanan',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'komut ayrıntıları',
	MSGRETURN:'(geri dön)',
	MSGGENBBCODE:'BBKodu listesi oluştur',
	MSGDEFSITE:'Öldürdüğün....',
	MSGLOSSITE:'Kayıpların...',
	MSGASATT:'...saldırgan olarak',
	MSGASDEF:'...savunmacı olarak',
	MSGDIFF1:'farklılıkları gösterme',
	MSGDIFF2:'farklılıkları göster',
	MSGDIFF3:'sadece farklılıkları göster',
	BBCODELIMIT:'Metin uzun bir liste ise, veri gruba ayrılır. Her grubu ayrı bir girdi olarak kopyalayıp yapıştırın.',
	CHKPOWERNAME:'Büyüler için gerekli teveccühlerin yüklenme sürelerini göster',
	CHKFORUMTABS:'Forum sekme pencerelerini sırala',
	STATSLINK:'İstatistikler için',
	BTNSUPPLAYERS:'Oyuncu listesi',
	CHKUNITSCOST:'Kaybedilen birimlerin maliyet raporu',
	CHKOCEANNUMBER:'Deniz numaralarını göster',
	MSGRTLBL:'Ayaklanma Bilgisi',
	MSGRTSHOW:'Devem eden Ayaklanma Bilgisi ekle',
	MSGRTONLINE:'Ayaklanma başladığında çevrimiçi olacak mısın?',
	MSGRTYES:'Evet',
	MSGRTNO:'Hayır',
	MSGRTGOD:'Tanrı',
	MSGRTCSTIME:'Koloni zamanı',
	MSGRTONL:'çevrimiçi?',
	MSGRTERR:'Yanlış Şehirdesin!<br/>Bilgiyi oluşturmak için şu şehire git: ',
	BBTEXT:'yazı şekinde',
	BBHTML:'tablo şeklinde',
	MSG413ERR:'<h3>Oluşturulan rapor çok büyük.</h3><p>Seçenekler kısmından ayarları değiştirirseniz sorunu çözebilirsiniz.</p>',
	CHKREPORTFORMAT:'Tablo kullanarak raporları oluştur',
	WALLNOTSAVED:'Şehir surları kaydedilmedi',
	WALLSAVED:'Şehir surları kaydedildi',
	POPSELRECRUNIT:'Varsayılan üretim birimi seçmek için tıklayın',
	POPRECRUNITTRADE:'seçili birimi oluşturmak için hammadde doldurmak için tıkla',
	POPINSERTLASTREPORT:'Dönüştürülen son raporu yayınla',
	MSGCOPYREPORT:'Rapor kaydedildi. Bu raporu yayınlamak için forum yada yeni mesaj penceresinde bu [paste_icon] logoya tıklayın.',
	POPDISABLEALARM:'Alarmı kapat',
	SOUNDSETTINGS:'Ses ayarı',
	CHKSOUNDMUTE:'Sessiz',
	SOUNDVOLUME:'Ses',
	SOUNDURL:'Ses dosyası adresi',
	CHKSOUNDLOOP:'Tekrar',
	POPSOUNDLOOP:'Tekrar oynat',
	POPSOUNDMUTE:'Sesi kıs',
	POPSOUNDPLAY:'Oynat',
	POPSOUNDSTOP:'Durdur',
	POPSOUNDURL:'yüklenen ses dosyasının adresi',
	STATS:{
		PLAYER:'Oyuncu istatistiği',
		ALLY:'İttifak istatistiği',
		TOWN:'Şehir istatistiği',
		INACTIVEDESC:'bu süre içinde savaş puanı yapmadı ve şehir büyütmedi',
		CHKINACTIVE:'Pasif Oyuncular',
		INACTIVE:'Pasif',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Birim Toplama Yardımcısı',
			UNITFRAME:'biriminizi seçin',
			DESCRIPTION1:'Bu şehide [population] özgür nüfus var',
			DESCRIPTION2:'inşaat yapmak için yeterli olan [max_units]',
			DESCRIPTION3:'Bu [yesno] araştırmayı tamamladın [research].',
			DESCRIPTION4:'En fazla [max_queue] kadar birim sıraya koyabilirsin',
			TARGET:'inşaat yapmak istediğin hedefi seç',
			PACKAGE:'Taşıma başına hammadde miktarı(units)',
			BTNSAVE:'ayarları kaydet',
			TOOLTIPOK:'Hammadde gönderceceğin varsayılan birimi seçmek için tıkla',
			TOOLTIPNOTOK:'teknoloji akademide araştırılmamış',
			HASRESEARCH:'YAP',
			NORESEARCH:'YAPMA',
			SETTINGSAVED:'[city] için ayarlar kaydedildi',
		},
		RESWND:{
			RESLEFT:'yollayabileceğin kalan hammadde',
			IMGTOOLTIP:'hammaddeyi doldurmak için tıkla',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Yeni versiyon mevcut',
		INSTALL:'Yükle',
		REMINDER:'Daha sonra hatırlat',
		REQRELOAD:'Sitenin yenilenmesi gerekiyor.',
		RELOAD:'Yenile',
	},
	LANGS:{
		LANG:'Çevirilen dil:',
		SEND:'Çeviriyi Gönder',
		SAVE:'Kaydet & Test Et',
		RESET:'Varsayılan dile sıfırla',
		REMOVE:'Çevirini silmek istediğine emin misin?',
	},
	HELPTAB5:'Çeviri',
	BTNSIMUL:'Simülatör',
	EMOTS:{
		LABEL:'Daha fazla ifade ister misin?',
		MESS:'Her yeni bir ifade için yeni bir satıra bağlantı yapıştırın...',
	},
	COMMAND:{
		ALL:'Hepsi',
		INCOMING:'Gelen',
		OUTGOING:'Giden',
		RETURNING:'Dönen',
		FORTOWN:'şehir:',
	},
	MOBILEVERSION:'Mobil Versiyonu',
	AO:{
		TITLE:'Akademi Araştırmaları',
	},
	TSL:{
		WND:{
			TOOLTIP:'Şehirleri Sırala',
			WINDOWTITLE:'Şehir Listesi',
		},
	},
	CHKOLDTRADE:'Eski ticaret sistemini kullan',
	QUESTION:'Soru',
	WALL:{
		WANTDELETECURRENT:'Surların günlük kaydını silmek istiyor musunuz?',
		DELETECURRENT:'Kaydı sil',
		LISTSTATE:'Kaydedilen Surların tarihi',
		LISTSAVED:'Surları günlük kaydet',
	},
	RADAR:{
		ALL:'Herhangi bir Şehir',
		BTNSAVEDEFAULT:'Varsayılan olarak kaydet',
		TOWNPOINTS:'Şehir Puanı',
		TOWNRESERVED:'Rezervasyon',
		TOWNOWNER:'Sahip',
		CSTIME:'Koloni Zamanı',
		TOWNNAME:'Şehir',
		BTNFIND:'Ara',
		MAXCSTIME:'Koloni mesafe süresi',
		FIND:'Ara',
		TOWNFINDER:'Şehir Arama',
	},
	POPSOUNDEG:'Örnek: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	MSGSHOWCOST:'Kaybedilen birimlerin maliyeti',
	BTNVIEWBB:'BBKodu',
	LASTUPDATE:'1487501618596',
}