RepConvLangArray.sk = {
	AUTHOR:' , DragonKnight, jaro868, tekri, Aeris, ado329',
	BTNCONV:'Previesť',
	BTNGENER:'Vytvoriť',
	BTNVIEW:'Ukážka',
	BTNSAVE:'Uložiť',
	MSGTITLE:'Previesť správu',
	MSGQUEST:'Ktoré z dát chcete publikovať?',
	MSGBBCODE:'Po zverejnení správy, môžete spárovať s novinkami a fórom pomocou BBCode.',
	MSGRESOURCE:'Korisť',
	MSGUNITS:'Jednotky',
	MSGBUILD:'Stavby',
	MSGUSC:'Použitých strieborných mincí',
	MSGRAW:'Suroviny',
	SUPPORT:'Podpora',
	SPY:'Špehovanie',
	CONQUER:'Zvíťazil',
	LOSSES:'Straty',
	HIDDEN:'Skryté',
	NOTUNIT:'[i]žiadny[/i]',
	TOWN:'[i]Mesto:[/i] ',
	PLAYER:'[i]Hráč:[/i] ',
	ALLY:'[i]Spojenectvo:[/i] ',
	CAST:'obsadenie:',
	ONTOWER:'V meste:',
	MSGHIDAD:'Skryté mestá',
	MSGFORUM:'Táto správa bude zverejnená',
	BBALLY:'spojenecké fórum / v správe',
	BBFORUM:'externé fórum',
	ICOCLOSE:'Zavrieť',
	ICOHELP:'O prevodníku',
	MSGPREVIEW:'<b>Zobraziť správu</b>',
	HELPTAB1:'O ',
	HELPTAB2:'Ako to funguje',
	HELPTAB3:'Zmeny',
	HELPTAB4:'Nastavenia',
	MSGHUMAN:{
		OK:'Informácie boli uložené',
		ERROR:'Vyskytla sa chyba pri písaný',
		YOUTUBEERROR:'Nesprávny link, alebo nieje povolené na prehrávanie mimo youtube',
	},
	LABELS:{
		attack:{
			ATTACKER:'Utočník',
			DEFENDER:'Obranca',
			MSGHIDAT:'Utočník',
			MSGHIDDE:'Obranca',
			MSGATTUNIT:'Utočiaca armáda',
			MSGDEFUNIT:'Obranujúca armáda',
		},
		support:{
			ATTACKER:'Supporting',
			DEFENDER:'Supported',
			MSGHIDAT:'supporting',
			MSGHIDDE:'supported',
			MSGATTUNIT:'Army supporting',
			MSGDEFUNIT:'Army defenders',
		},
		espionage:{
			ATTACKER:'Špión',
			DEFENDER:'Špehovaný',
			MSGHIDAT:'Špión',
			MSGHIDDE:'špehovaný',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'detaily príkazu',
	MSGRETURN:'(späť)',
	MSGGENBBCODE:'Vytvoriť zoznam v BBCode',
	MSGDEFSITE:'Porazení...',
	MSGLOSSITE:'Straty...',
	MSGASATT:'...ako útočník',
	MSGASDEF:'...ako obranca',
	MSGDIFF1:'nezobraziť rozdiely',
	MSGDIFF2:'zobraziť rozdiely',
	MSGDIFF3:'zobraziť iba rozdiely',
	BBCODELIMIT:'Vzhľadom k obmedzenému množstvu textu v jednej správe, v prípade dlhého zoznamu, boli dáta rozdelená do skupín. Každú skupinu vložiť ako samostatný vstup.',
	CHKPOWERNAME:'Zobrazenie zostávajúceho času na možnosť použitia kúzla',
	CHKFORUMTABS:'Vymeniť rolovanie zarážky na fóre multi line',
	STATSLINK:'Štatistiky z displeja',
	BTNSUPPLAYERS:'Zoznam hráčov',
	CHKUNITSCOST:'Správa zobrazuje náklady stratených jednotiek',
	CHKOCEANNUMBER:'Zobraziť číslo mora',
	MSGRTLBL:'Informácie o vzbure',
	MSGRTSHOW:'Pridať priebežné informácie o odboji',
	MSGRTONLINE:'Chystáš sa byť on-line v priebehu červenej vzbury?',
	MSGRTYES:'Áno',
	MSGRTNO:'Nie',
	MSGRTGOD:'Boh',
	MSGRTCSTIME:'Čas OL',
	MSGRTONL:'on-line?',
	MSGRTERR:'Ste v zlom meste <br/> Ak chcete vytvoriť informácie o vzbure choďte do mesta !:',
	BBTEXT:'verzia s textom',
	BBHTML:'verzia s tabuľkou',
	MSG413ERR:'<H3> generovaná správa je príliš veľká. </h3><p> Použite dostupné možnosti a zredukujte publikované bez problémov. </p>',
	CHKREPORTFORMAT:'Vytvoriť report pomocou tabuliek',
	WALLNOTSAVED:'Hradby nie sú uložené',
	WALLSAVED:'Hradby sú uložené',
	POPSELRECRUNIT:'click, to select default production unit',
	POPRECRUNITTRADE:'click, to fill in resources needed to recruit selected unit',
	POPINSERTLASTREPORT:'Prilepiť posledne konvertované hlásenie',
	MSGCOPYREPORT:'The report has been saved. Please click [paste_icon] on forums or new message window to paste it',
	POPDISABLEALARM:'Vypnúť alarm',
	SOUNDSETTINGS:'Nastavenia zvuku',
	CHKSOUNDMUTE:'Vypnúť zvuk',
	SOUNDVOLUME:'Hlasitosť',
	SOUNDURL:'URL zvuku',
	CHKSOUNDLOOP:'slučka',
	POPSOUNDLOOP:'Prehrať v slučke',
	POPSOUNDMUTE:'Stlmiť zvuk',
	POPSOUNDPLAY:'Hrať s aktuálnym nastavením',
	POPSOUNDSTOP:'Prestať hrať',
	POPSOUNDURL:'Url path to the file with sound',
	STATS:{
		PLAYER:'Štatistiky hráča',
		ALLY:'Štatistiky spojenectva',
		TOWN:'Štatistiky mesta',
		INACTIVE:'Neaktívny',
		CHKINACTIVE:'Ukázať neaktívnych hráčov',
		INACTIVEDESC:'Čas, kedy nebol zaznamenaný žiaden bojový bod a bod za stavbu',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Pomocník na stavanie armády',
			UNITFRAME:'vyber si svoje jednotky',
			DESCRIPTION1:'Voľná populácia v tomto meste je [population] ',
			DESCRIPTION2:'Čo je dosť na  [max_units]',
			DESCRIPTION3:'[yesno] vyskúmané [research]',
			DESCRIPTION4:'Môžeš vytrénovať maximálne [max_queue] jednotiek',
			TARGET:'vyber si počet',
			PACKAGE:'resource package per shipment (units)',
			BTNSAVE:'uložiť nastavenia',
			TOOLTIPOK:'click, to select default unit for which you\'ll be sending resources',
			TOOLTIPNOTOK:'jednotka ešte nebola vyskúmaná',
			HASRESEARCH:'Máš',
			NORESEARCH:'Nemáš',
			SETTINGSAVED:'Nastavenie pre [city] bolo uložené',
		},
		RESWND:{
			RESLEFT:'resources left to send',
			IMGTOOLTIP:'kliknite, pre zaplnenie surovín',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Nová verzia dostupná',
		INSTALL:'Inštalovať',
		REMINDER:'Pripomenúť neskôr',
		REQRELOAD:'Obnovenie je nevyhnutné',
		RELOAD:'Obnoviť',
	},
	LANGS:{
		LANG:'Preložiť do jazyka:',
		SEND:'Send to publication',
		SAVE:'Uložiť a vyskúšať',
		RESET:'Nastaviť pôvodný jazyk',
		REMOVE:'Vymazať tvôj preklad?',
	},
	HELPTAB5:'Preklad',
	BTNSIMUL:'Simulátor',
	EMOTS:{
		LABEL:'Chceš viac smajlíkov?',
		MESS:'Prilep linky smajlíkov, každý do novej karty',
	},
	COMMAND:{
		ALL:'Všetky',
		INCOMING:'Prichádzajúce',
		OUTGOING:'Odchádzajúce',
		RETURNING:'Vracajúce sa',
		FORTOWN:'mesto:',
	},
	BTNVIEWBB:'BBkód',
	MSGSHOWCOST:'Náklady na stratené jednotky',
	POPSOUNDEG:'príklad: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	RADAR:{
		TOWNFINDER:'Nájsť mestá',
		FIND:'Hľadať',
		MAXCSTIME:'Maximálny čas kolonizačnej lode',
		CSTIME:'Čas OL',
		TOWNNAME:'Mesto',
		BTNFIND:'Hľadať',
		TOWNRESERVED:'Rezervácia',
		TOWNOWNER:'Vlastník',
		TOWNPOINTS:'Minimálny počet bodov mesta',
		BTNSAVEDEFAULT:'Uložiť hodnoty ako štandardné',
		ALL:'Akékoľvek mesto',
	},
	WALL:{
		LISTSAVED:'Hradby boli uložené dňa',
		LISTSTATE:'Stav hradieb na deň',
		DELETECURRENT:'Odstrániť súčasný záznam',
		WANTDELETECURRENT:'Ste si istý, že chcete odstrániť súčasný záznam ?',
	},
	QUESTION:'Otázka',
	MOBILEVERSION:'Mobilná verzia',
	AO:{
		TITLE:'Prehľad akadémie',
	},
	LASTUPDATE:'1487502170884',
}