RepConvLangArray.nl = {
	INFO:{
		0:'Potusek',
		1:'grepolis@potusek.eu',
	},
	WEBSITE:'Website',
	AUTHOR:'zippohontas@gmail.com, jestertje, Gotcha8, gwvelden, Frosty Jim',
	BTNCONV:'Converteer',
	BTNGENER:'Genereer',
	BTNSRC:'Bron',
	BTNVIEW:'Voorbeeld',
	BTNSAVE:'Opslaan',
	BTNMARKS:'Gemarkeerd als gelezen',
	BTNMARKA:'Markeer alle als gelezen',
	MSGTITLE:'Converteer rappport',
	MSGQUEST:'Welke data wil je publiceren?',
	MSGALL:'Alle',
	MSGBBCODE:'Volgens de publicatie van het rapport, kun je het combineren met nieuws en forums door gebruik te maken van de BBCode.',
	MSGRESOURCE:'Buit',
	MSGUNITS:'Eenheden',
	MSGBUILD:'Gebouwen',
	MSGUSC:'Gebruikt zilver',
	MSGRAW:'Grondstoffen',
	SUPPORT:'Ondersteuning',
	SPY:'Spionage',
	CONQUER:'Overwonnen',
	LOSSES:'Verliezen',
	HIDDEN:'Verborgen',
	NOTUNIT:'[i]Geen[/i]',
	TOWN:'[i]Stad:[/i] ',
	PLAYER:'[i]Speler:[/i] ',
	ALLY:'[i]Allie:[/i] ',
	CAST:'gunst:',
	ONTOWER:'Op de stad:',
	MSGHIDAD:'Verberg steden',
	MSGFORUM:'Het rapport wordt gepubliceerd',
	BBALLY:'alliantie forums / in het bericht',
	BBFORUM:'externe forum',
	ERRGETSRC:'Een fout is opgetreden! AUB, genereer de bron en verstuur als bijlage aan potusek@westtax.info',
	ICOCLOSE:'Sluiten',
	ICOHELP:'Over de converteerder',
	MSGPREVIEW:'<b>Rapport voorbeeld</b>',
	HELPTAB1:'Over',
	HELPTAB2:'Hoe werkt het',
	HELPTAB3:'Veranderingen',
	HELPTAB4:'Instellingen',
	HLPVERSION:'Versie',
	HLPFIXED:'Fixed',
	HLPADDED:'Toegevoegd',
	MSGHUMAN:{
		OK:'De informatie is opgeslagen',
		ERROR:'Er is een fout opgetreden tijdens het schrijven ',
		YOUTUBEERROR:'Verkeerde link of niet toegestaan af te spelen buiten YouTube',
	},
	STATS:'Speler statistieken',
	STATSPOINT:'Punten',
	STATSRANK:'Rang',
	LABELS:{
		attack:{
			ATTACKER:'Aanvaller',
			DEFENDER:'Verdediger',
			MSGHIDAT:'aanvaller',
			MSGHIDDE:'verdediger',
			MSGATTUNIT:'Aanvallend Leger',
			MSGDEFUNIT:'Verdedigend Leger',
		},
		support:{
			ATTACKER:'Ondersteunen',
			DEFENDER:'Ondersteunde',
			MSGHIDAT:'ondersteunen',
			MSGHIDDE:'ondersteunde',
			MSGATTUNIT:'Ondersteunend Leger',
			MSGDEFUNIT:'Verdedigend Leger',
		},
		espionage:{
			ATTACKER:'Spion',
			DEFENDER:'Bespioneerde',
			MSGHIDAT:'spion',
			MSGHIDDE:'bespioneerde',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'commando details',
	MSGRETURN:'(enter)',
	MSGCLAIM:'city ??claims',
	MSGCLAIMPPUP:'Genereer claim',
	MSGGENBBCODE:'Genereer een lijst in BBCode',
	MSGDEFSITE:'Verslagen...',
	MSGLOSSITE:'Verliezen...',
	MSGASATT:'...als aanvaller',
	MSGASDEF:'...als verdediger',
	MSGDIFF1:'laat niet de verschillen zien',
	MSGDIFF2:'laat verschillen zien',
	MSGDIFF3:'laat enkel de verschillen zien',
	BBCODELIMIT:'Vanwege gelimiteerde hoeveelheid tekst in een bericht, in het geval van een lange lijst, de data is onderverdeeld in groepen. Elke groep in een apart bericht plakken.',
	CHKPOWERNAME:'Toon de tijd tot mogelijk gebruik van de gunst',
	CHKNIGHTNAME:'Verduisterd de stad tijdens nacht bonus',
	CHKFORUMTABS:'Vervang scrollen van de forum tabs door meerdere regels',
	BTNRESERVE:'Claim',
	LNKRESERVE:'Claims',
	LBLGETRESER:'Data ophalen...',
	BTNCHECK:'Controle Claims',
	CHKCMDIMG:'View the icons for the destination city commands',
	STATSLINK:'Statistieken van deze pagina laden',
	BTNSUPPLAYERS:'Lijst met spelers',
	CHKUNITSCOST:'Het rapport de kosten van de verloren eenheden laten tonen',
	CHKOCEANNUMBER:'Oceaannummers laten zien',
	MSGRTLBL:'Opstandsinformatie',
	MSGRTSHOW:'Voeg bezigzijnde opstandsinformatie toe',
	MSGRTONLINE:'Ben je online tijdens fase rood?',
	MSGRTYES:'Ja',
	MSGRTNO:'Nee',
	MSGRTCSTIME:'Koloschip vaartijd',
	MSGRTERR:'Je kijkt naar de verkeerde stad!<br/> Ga naar de stad om de opstandsinformatie te maken: ',
	BBTEXT:'Tekst versie',
	BBHTML:'Tabel versie',
	MSG413ERR:'<h3>Het gegenereerde rapport is te groot</h3><p>Gebruik de aanwezige mogelijkheden en verklein het om publiceerproblemen te voorkomen</p>',
	CHKREPORTFORMAT:'Genereer rapporten door middel van tabellen',
	WALLNOTSAVED:'De muur is niet opgeslagen',
	WALLSAVED:'De muur is opgeslagen',
	POPSELRECRUNIT:'Klik, om de standaard productie-eenheid te selecteren',
	POPRECRUNITTRADE:'Klik, om de grondstoffen benodig voor de geselecteerde eenheid in te vullen',
	POPINSERTLASTREPORT:'Plak het laatst geconverteerde rapport',
	MSGCOPYREPORT:'Het rapport is  opgeslagen. Klik op[paste_icon]op de fora of op een nieuw berichtscherm, om het te posten',
	POPDISABLEALARM:'Schakel het alarm uit',
	SOUNDSETTINGS:'Geluid instellingen',
	CHKSOUNDMUTE:'Geluid uit',
	POPSOUNDLOOP:'In loop afspelen',
	POPSOUNDMUTE:'Het geluid uitzetten',
	POPSOUNDPLAY:'Speel af met deze instellingen',
	POPSOUNDSTOP:'Stop afspelen',
	POPSOUNDURL:'Url naar het bestand van het geluid',
	ABH:{
		WND:{
			WINDOWTITLE:'Legeraanbouw helper',
			UNITFRAME:'Kies je eenheid',
			DESCRIPTION1:'In deze stad heb je [population] vrije inwoners',
			DESCRIPTION2:'Wat genoeg is om  [max_units] te bouwen',
			DESCRIPTION3:'Je hebt [yesno] [research] onderzocht',
			DESCRIPTION4:'Je kan in de wachtrij[max_queue] eenheden zetten',
			TARGET:'Kies je bouwdoel',
			PACKAGE:'Grondstoffen per lading (units)',
			BTNSAVE:'Slaat instellingen op',
			TOOLTIPOK:'klik, om de standaard eenheid in te stellen waarvoor je grondstoffen zult zenden',
			TOOLTIPNOTOK:'Eenheid is nog niet onderzocht',
			SETTINGSAVED:'Instelling voor [city] zijn opgeslagen',
			HASRESEARCH:'DOE',
			NORESEARCH:'DOE NIET',
		},
		RESWND:{
			RESLEFT:'Grondstoffen nog te sturen',
			IMGTOOLTIP:'klik, om de grondstoffen in te vullen',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Er is een nieuwe versie beschikbaar',
		INSTALL:'Installeer ',
		REMINDER:'Herinner mij later',
		REQRELOAD:'Het is nodig om de site opnieuw te laden',
		RELOAD:'Opnieuw laden',
	},
	LANGS:{
		LANG:'Vertaling voor taal:',
		SEND:'Verzonden naar publicatie',
		SAVE:'Opslaan en testen',
		RESET:'Herstel de standaardtaal',
		REMOVE:'Verwijder je vertaling?',
	},
	HELPTAB5:'Vertaling',
	COMMAND:{
		ALL:'Alle',
		INCOMING:'inkomend',
		OUTGOING:'uitgaand',
		RETURNING:'terugkomend',
		FORTOWN:'stad:',
	},
	MSGSHOWCOST:'Kosten van verloren eenheden',
	BBIMG:'enkele afbeelding',
	LASTUPDATE:'1488490764765',
	SOUNDVOLUME:'Geluids Volume',
	SOUNDURL:'Geluidsbestand url',
	POPSOUNDEG:'voorbeeld: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	EMOTS:{
		LABEL:'Wil je meer emoticons?',
		MESS:'Plak links naar emoticons, elk op een nieuwe regel',
	},
	RADAR:{
		TOWNFINDER:'Zoek steden',
		FIND:'Zoek',
		MAXCSTIME:'Maximale tijd kolonisatieschip',
		BTNFIND:'Zoek',
		TOWNNAME:'Stad',
		TOWNOWNER:'Eigenaar',
		TOWNRESERVED:'Reservering',
		TOWNPOINTS:'Minimale stadspunten',
		BTNSAVEDEFAULT:'Sla waarden op als standaard',
		ALL:'Elke Stad',
		UNITTIME:'tijd',
		MAXUNITTIME:'Maximale tijd',
	},
	WALL:{
		LISTSAVED:'Opgeslagen muur op de dag',
		LISTSTATE:'Toestand van de muur op de dag',
		DELETECURRENT:'Verwijder het huidige bestand',
		WANTDELETECURRENT:'Wil je het huidige muur-bestand verwijderen?',
	},
	QUESTION:'Vraag',
	TSL:{
		WND:{
			WINDOWTITLE:'Gesorteerde stedenlijst',
			TOOLTIP:'laat gesorteerde stad zien',
		},
	},
	CHKOLDTRADE:'Gebruik oude handels layout',
	AO:{
		TITLE:'Academie overzicht',
	},
	MOBILEVERSION:'Mobiele versie',
	CHKWONDERTRADE:'Wanneer men grondstoffen naar wereldwonderen stuurt, stuur maximale gelijke hoeveelheid',
    CHKMOUSEWHEELZOOMBULLEYE: 'Gebruik muiswiel om de map te zoomen'
}