RepConvLangArray.pt = {
	AUTHOR:'100 noção, Cirrus Minor, AceCombat021, Dark Rebel, Difus, Eduslb98, Gwyneth Llewelyn, AceCombat021, Dark Rebel, Difus, Eduslb98, Gwyneth Llewelyn, zyka',
	BTNCONV:'Converter',
	BTNGENER:'Gerar',
	BTNVIEW:'Visualizar',
	BTNSAVE:'Salvar',
	MSGTITLE:'Converter Relatório',
	MSGQUEST:'Quais dados você deseja publicar ?',
	MSGBBCODE:'Uma vez o relatório publicado, pode partilhá-lo em notícias e fóruns usando BBCode.',
	MSGRESOURCE:'Saque',
	MSGUNITS:'Unidades',
	MSGBUILD:'Edifícios',
	MSGUSC:'Moedas de prata usadas',
	MSGRAW:'Recursos da Cidade',
	SUPPORT:'Suporte',
	SPY:'Espionagem',
	CONQUER:'Conquistas',
	LOSSES:'Perdas',
	HIDDEN:'Omitido',
	NOTUNIT:'[i]Nenhum[/i]',
	TOWN:'[i]Cidade:[/i] ',
	PLAYER:'[i]Jogador:[/i] ',
	ALLY:'[i]Aliança:[/i] ',
	CAST:'Lançar:',
	ONTOWER:'Na Cidade:',
	MSGHIDAD:'Esconder cidades',
	MSGFORUM:'O relatório será publicado',
	BBALLY:'Fóruns da aliança / na mensagem',
	BBFORUM:'Fórum Externo',
	ICOCLOSE:'Fechar',
	ICOHELP:'Sobre o conversor',
	MSGPREVIEW:'<b>Pré visualização do Relatório</b>',
	HELPTAB1:'Sobre',
	HELPTAB2:'Como funciona',
	HELPTAB3:'Mudanças',
	HELPTAB4:'Configurações',
	MSGHUMAN:{
		OK:'Informação salva com sucesso',
		ERROR:'Ocorreu um erro ao salvar',
		YOUTUBEERROR:'Link incorreto ou não disponível fora do youtube',
	},
	LABELS:{
		attack:{
			ATTACKER:'Atacante',
			DEFENDER:'Defensor',
			MSGHIDAT:'Atacante',
			MSGHIDDE:'defensor',
			MSGATTUNIT:'Unidades de Ataque',
			MSGDEFUNIT:'Unidades de Defesa',
		},
		support:{
			ATTACKER:'Apoiando',
			DEFENDER:'Apoiado',
			MSGHIDAT:'Apoiando',
			MSGHIDDE:'Apoiado',
			MSGATTUNIT:'Unidades apoiando',
			MSGDEFUNIT:'Unidades Defendendo',
		},
		espionage:{
			ATTACKER:'Espião',
			DEFENDER:'Espiado',
			MSGHIDAT:'Espião',
			MSGHIDDE:'Espiado',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'Detalhes do Comando',
	MSGRETURN:'(retornar)',
	MSGGENBBCODE:'Gerar lista de BBcode',
	MSGDEFSITE:'Derrotado...',
	MSGLOSSITE:'Perdas...',
	MSGASATT:'...Como atacante',
	MSGASDEF:'...Como defensor',
	MSGDIFF1:'Não mostrar diferenças',
	MSGDIFF2:'Mostrar diferenças',
	MSGDIFF3:'Mostrar apenas as diferenças',
	BBCODELIMIT:'Tendo em vista um número limitado de caracteres em um post, no caso de uma lista longa, os dados serão divididos em grupos, cada grupo postado separadamente.',
	CHKPOWERNAME:'Tempo restante para poder usar o encantamento',
	CHKFORUMTABS:'Substituir guias de rolagem do fórum para uma guia paralela',
	STATSLINK:'Estatísticas no visor',
	BTNSUPPLAYERS:'Lista de jogadores',
	CHKUNITSCOST:'O Relatório mostra o custo das unidades perdidas',
	CHKOCEANNUMBER:'Exibir número do oceano',
	MSGRTLBL:'Informações sobre a revolta',
	MSGRTSHOW:'Adicionar informação de revolta em curso',
	MSGRTONLINE:'Você estará online durante a mão de fogo ?',
	MSGRTYES:'Sim',
	MSGRTNO:'Não',
	MSGRTGOD:'Deus',
	MSGRTCSTIME:'Tempo de NC',
	MSGRTONL:'Conectado ?',
	MSGRTERR:'Você está na cidade errada!<br/>Para criar a informação de revolta, por favor vá para a cidade:',
	BBTEXT:'Versão em Texto',
	BBHTML:'Versão em Tabela',
	MSG413ERR:'<h3>O relatório gerado é muito grande.</h3><p>Use as opções disponíveis para reduzir e publicar sem problemas.</p>',
	CHKREPORTFORMAT:'Gerar relatórios usando Tabela',
	WALLNOTSAVED:'Muralha não foi salva',
	WALLSAVED:'Muralha foi salva',
	POPSELRECRUNIT:'Clique, para selecionar a unidade de produção padrão',
	POPRECRUNITTRADE:'Clique, para preencher os recursos necessários para recrutar a unidade selecionada',
	POPINSERTLASTREPORT:'Colar o último relatório convertido',
	MSGCOPYREPORT:'O relatório foi salvo. Por favor, clique em [paste_icon] no fórum ou em nova janela de mensagem para colá-lo',
	POPDISABLEALARM:'Desativar alarme',
	SOUNDSETTINGS:'Configurações de som',
	CHKSOUNDMUTE:'Mudo',
	SOUNDVOLUME:'Volume',
	SOUNDURL:'Link de som',
	CHKSOUNDLOOP:'ciclo',
	POPSOUNDLOOP:'percorrer ciclo',
	POPSOUNDMUTE:'Mutar o som',
	POPSOUNDPLAY:'Jogar com as configurações atuais',
	POPSOUNDSTOP:'Parar execução',
	POPSOUNDURL:'Caminho de url para o arquivo com som',
	STATS:{
		PLAYER:'Status do Jogador',
		ALLY:'Status da Aliança',
		TOWN:'Status da Cidade',
		INACTIVE:'Inativo',
		CHKINACTIVE:'Mostrar Jogadores Inativos',
		INACTIVEDESC:'Neste tempo não houve pontos ganhos atacando ou expandindo.',
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Construtor de Exércitos',
			UNITFRAME:'Selecione sua unidade',
			DESCRIPTION1:'Nessa cidade, você tem [population] população livre',
			DESCRIPTION2:'Qual é o suficiente para construir [max_units]',
			DESCRIPTION3:'Você [yesno] Tem [research] Pesquisado.',
			DESCRIPTION4:'Você pode enfileirar um máximo de [max_queue] unidades',
			TARGET:'Selecione sua cidade alvo',
			PACKAGE:'Pacote de Recursos por vez (units)',
			BTNSAVE:'Salvar configurações',
			TOOLTIPOK:'Clique para selecionar a unidade padrão a qual você estará enviando recursos',
			TOOLTIPNOTOK:'A unidade não foi pesquisada',
			HASRESEARCH:'Fazer',
			NORESEARCH:'Não fazer',
			SETTINGSAVED:'Configurações de [city] Foram salvas',
		},
		RESWND:{
			RESLEFT:'Recursos excedentes para envio',
			IMGTOOLTIP:'Clique, para preencher os recursos',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Nova versão disponível',
		INSTALL:'Instalar',
		REMINDER:'Lembrar mais tarde',
		REQRELOAD:'Atualização requerida',
		RELOAD:'Atualizar',
	},
	LANGS:{
		LANG:'Traduzido para o idioma:',
		SEND:'Enviar para publicação',
		SAVE:'Salvar e testar',
		RESET:'Restaurar idioma padrão',
		REMOVE:'Excluir sua tradução ?',
	},
	HELPTAB5:'Tradução',
	BTNSIMUL:'Simulador',
	EMOTS:{
		LABEL:'Quer mais emoctions ?',
		MESS:'Cole links para emoction, cada um em uma nova linha',
	},
	COMMAND:{
		ALL:'Todos',
		INCOMING:'A chegar',
		OUTGOING:'A partir',
		RETURNING:'A regressar',
		FORTOWN:'cidade:',
	},
	MSGSHOWCOST:'Custo de unidades perdidas',
	BBIMG:'imagem única ',
	POPSOUNDEG:'exemplo: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	RADAR:{
		FIND:'Procurar',
		TOWNFINDER:'Procurar Cidades',
		MAXCSTIME:'Tempo máximo para NC',
		TOWNPOINTS:'Pontos mínimos da cidade',
		TOWNRESERVED:'Reservas',
		TOWNOWNER:'Dono',
		BTNSAVEDEFAULT:'Salvar valores como padrão',
		ALL:'Qualquer cidade',
		BTNFIND:'Procurar',
		TOWNNAME:'Cidade',
		CSTIME:'Tempo CS',
	},
	WALL:{
		LISTSTATE:'Condição da muralha no dia',
		DELETECURRENT:'Apagar o registo corrente',
		LISTSAVED:'Muralha salva no dia',
		WANTDELETECURRENT:'Quer apagar o registo corrente no cronograma?',
	},
	QUESTION:'Questão',
	CHKWONDERTRADE:'Ao enviar recursos para maravilhas do mundo, enviar quantidades máximas iguais',
	MOBILEVERSION:'Versão móvel',
	AO:{
		TITLE:'Visão geral da academia',
	},
	CHKOLDTRADE:'Usar anterior esquema de comércio',
	TSL:{
		WND:{
			TOOLTIP:'mostrar cidade ordenada',
			WINDOWTITLE:'Lista de cidades ordenada',
		},
	},
	LASTUPDATE:'1487531813324',
}