RepConvLangArray.ro = {
	INFO:{
		0:'Potusek',
		1:'grepolis@potusek.eu',
	},
	WEBSITE:'Website',
	AUTHOR:'Autor, Sir Prize, magicianul2006, EnsyFane, LLTCM',
	BTNCONV:'Converteste',
	BTNGENER:'Genereaza',
	BTNSRC:'Sursa',
	BTNVIEW:'Previzualizare',
	BTNSAVE:'Salveaza',
	BTNMARKS:'Marcheaza ca citit',
	BTNMARKA:'Marcheaza tot ca citit',
	MSGTITLE:'Converteste Raportul',
	MSGQUEST:'Ce informatii din data vrei sa publici?',
	MSGALL:'Tot',
	MSGBBCODE:'Urmarind publicarea raportului, puteti sa il asociati cu noutati si forumuri folosind BBCode.',
	MSGRESOURCE:'Prada',
	MSGUNITS:'Soldați',
	MSGBUILD:'Cladiri',
	MSGUSC:'Monede de argint utilizate',
	MSGRAW:'Materii prime',
	SUPPORT:'Sprijin',
	SPY:'Spionat',
	CONQUER:'Cucerit',
	LOSSES:'Pierderi',
	HIDDEN:'Ascunde',
	NOTUNIT:'[i]Nimic[/i]',
	TOWN:'[i]Oraș:[/i] ',
	PLAYER:'[i]Jucător:[/i] ',
	ALLY:'[i]Alianță:[/i] ',
	CAST:'Folosire:',
	ONTOWER:'În oraș:',
	MSGHIDAD:'Ascunde oraș',
	MSGFORUM:'Raportul va fi publicat',
	BBALLY:'forumurile alianței / în mesaje',
	BBFORUM:'forum extern',
	ERRGETSRC:'O eroare a avut loc! Va rugam, trimiteti sursa ca o atasare la potusek@westtax.info',
	ICOCLOSE:'Închide',
	ICOHELP:'Despre convertor',
	MSGPREVIEW:'<b>Previzualizare raport</b>',
	HELPTAB1:'Despre',
	HELPTAB2:'Cum funcționează',
	HELPTAB3:'Schimbări',
	HELPTAB4:'Setări',
	HLPVERSION:'Versiune',
	HLPFIXED:'Fixat',
	HLPADDED:'Adaugat',
	MSGHUMAN:{
		OK:'Informatiile au fost salvate',
		ERROR:'O eroare a avut loc in timpul tiparirii',
		YOUTUBEERROR:'Link incorect sau nu este posibila redarea inafara youtube',
	},
	STATS:'Statisticile jucatorului',
	STATSPOINT:'Puncte',
	STATSRANK:'Rang',
	LABELS:{
		attack:{
			ATTACKER:'Atacator',
			DEFENDER:'Aparator',
			MSGHIDAT:'atacator',
			MSGHIDDE:'aparator',
			MSGATTUNIT:'Armata atacatoare',
			MSGDEFUNIT:'Armata defensiva',
		},
		support:{
			ATTACKER:'Sprijin',
			DEFENDER:'Sprijinit',
			MSGHIDAT:'sprijin',
			MSGHIDDE:'sprijinit',
			MSGATTUNIT:'Armata sprijin',
			MSGDEFUNIT:'Armata aparatori',
		},
		espionage:{
			ATTACKER:'Spion',
			DEFENDER:'Spionat',
			MSGHIDAT:'spion',
			MSGHIDDE:'spionat',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'deatalii comanda',
	MSGRETURN:'(inapoi)',
	MSGCLAIM:'oras ​​rezervare',
	MSGCLAIMPPUP:'Genereaza rezervare',
	MSGGENBBCODE:'Generează o listă de BBCode',
	MSGDEFSITE:'Infrant...',
	MSGLOSSITE:'Pierderi...',
	MSGASATT:'...ca atacator',
	MSGASDEF:'...ca apărător',
	MSGDIFF1:'nu arată diferențele',
	MSGDIFF2:'arată diferențele',
	MSGDIFF3:'arată doar diferențele',
	BBCODELIMIT:'Din cauza spațiului limitat pentru text într-o postare, în cazul unei liste lungi, informația a fost imparțită pe grupe. Fiecare grupă este separată.',
	CHKPOWERNAME:'Arată timpul rămas până la folosirea vrăjii',
	CHKNIGHTNAME:'Ascunde orasul in bonusul de noapte',
	CHKFORUMTABS:'Aranjează tab-urile de pe forum pe mai multe rânduri',
	BTNRESERVE:'Booking',
	LNKRESERVE:'Reservations',
	LBLGETRESER:'Noţiuni de bază de date ...',
	BTNCHECK:'Checking reservations',
	CHKCMDIMG:'View the icons for the destination city commands',
	STATSLINK:'Statistici de afișat',
	BTNSUPPLAYERS:'Lista jucătorilor',
	CHKUNITSCOST:'Afișarea costurilor unităților pierdute în raport',
	CHKOCEANNUMBER:'Arată numărul mării',
	MSGRTCSTIME:'Timp Nava Colonizare',
	MSGRTGOD:'Zeu',
	MSGRTNO:'Nu',
	MSGRTYES:'Da',
	MSGRTONLINE:'Vei fi online in timpul revoltei rosii? ',
	MSGRTSHOW:'Adauga informatii despre revolta in curs de desfasurare',
	MSGRTLBL:'Informația despre revoltă',
	MSGRTERR:'Ești în orasul greșit!<br/>Pentru a crea informația pentru revoltă, mergi te rog la orașul: ',
	BBHTML:'versiunea tabelată',
	BBTEXT:'versiunea text',
	MSG413ERR:'<h3>Raportul generat este prea mare.</h3><p>Folosește opțiunile valabile și reduse pentru a publica fără probleme.</p>',
	CHKREPORTFORMAT:'Generează rapoarte folosind tabele',
	WALLNOTSAVED:'Zidul nu a fost salvat',
	WALLSAVED:'Zidul a fost salvat',
	POPRECRUNITTRADE:'click, ca să folosești resursele necesare pentru recrutarea unității selectate',
	ABH:{
		WND:{
			WINDOWTITLE:'GRCRTools Ajutor Creator Armata',
			UNITFRAME:'alege-ti unitatea',
			DESCRIPTION1:'In acest oras ai [population] populatie libera',
			DESCRIPTION2:'Care este suficienta pentru a construi [max_units]',
			DESCRIPTION3:'Tu [yesno] ai cercetat [research].',
			DESCRIPTION4:'Poti sa adaugi in coada [max_queue] unitati',
			TARGET:'alege constructia',
			PACKAGE:'pachet de resurse pe expediere',
			BTNSAVE:'salveaza setarile',
			TOOLTIPOK:'click pentru a seta o unitate prestabilita pentru care vei trimite resurse',
			TOOLTIPNOTOK:'unitatile nu au fost cercetate',
			HASRESEARCH:'Fa',
			NORESEARCH:'Nu face',
			SETTINGSAVED:'Setarile pentru [city] au fost salvate',
		},
		RESWND:{
			RESLEFT:'resurse ramase pentru trimitere',
			IMGTOOLTIP:'click pentru a completa cu resurse',
		},
	},
	POPSOUNDURL:'Calea url a fișierului cu sunet',
	POPSOUNDSTOP:'Nu asculta',
	POPSOUNDPLAY:'Ascultă cu setările curente',
	POPSOUNDMUTE:'Închide sunetul',
	POPSOUNDLOOP:'Ascultă în buclă',
	CHKSOUNDLOOP:'buclă',
	SOUNDVOLUME:'Volum',
	SOUNDURL:'Sunetul fișierului url',
	CHKSOUNDMUTE:'Mut',
	SOUNDSETTINGS:'Setări pentru sunet',
	POPDISABLEALARM:'Dezactivează alarma',
	MSGCOPYREPORT:'Raportul a fost salvat. Te rog dă click [lipire_icon] pe forumuri sau pe noile mesaje din fereastra pentru lipire',
	POPINSERTLASTREPORT:'Lipește ultimul raport convertit',
	NEWVERSION:{
		AVAILABLE:'O noua versiune este disponibila',
		INSTALL:'Instaleaza',
		REMINDER:'Adu-mi aminte mai tarziu',
		REQRELOAD:'Reimprospatare nececsara',
		RELOAD:'Reimprospateaza',
	},
	LANGS:{
		LANG:'Traducere limba:',
		SEND:'Trimite catre editori',
		SAVE:'Salveaza si testeaza',
		RESET:'Seteaza limba prestabilita',
		REMOVE:'Sterge traducerea',
	},
	HELPTAB5:'Traducere',
	EMOTS:{
		LABEL:'Doresti mai multe emoticonuri?',
		MESS:'Lipeste link-ul catre emoticon, fiecare pe o noua linie',
	},
	COMMAND:{
		ALL:'toate',
		INCOMING:'vine',
		OUTGOING:'pleaca',
		RETURNING:'se intoarce',
		FORTOWN:'oras:',
	},
	CHKWONDERTRADE:'Cand se trimit resurse pentru minunile lumii, se trimit cantitati maxime si egale de resurse',
	MOBILEVERSION:'Versiunea mobila',
	AO:{
		TITLE:'Prezentare generală a Academiilor',
	},
	CHKOLDTRADE:'Foloseste configuratia veche pentru negot',
	TSL:{
		WND:{
			TOOLTIP:'arata orasele sortate',
			WINDOWTITLE:'Lista Sortata a Oraselor',
		},
	},
	QUESTION:'Intrebare',
	WALL:{
		WANTDELETECURRENT:'Doresti sa stergi inregistrarile curente ale zidului?',
		DELETECURRENT:'Sterge inregistrarile curente',
		LISTSTATE:'Conditia zidului in ziua',
		LISTSAVED:'Salvat pe zid in ziu',
	},
	RADAR:{
		ALL:'Orice oras',
		BTNSAVEDEFAULT:'Salveaza valorile ca implicite',
		TOWNPOINTS:'Puncte minime pe oras',
		TOWNRESERVED:'Rezervare',
		TOWNOWNER:'Detinator',
		CSTIME:'Timp Nava de Colonizare',
		BTNFIND:'Cauta',
		TOWNNAME:'Oras',
		MAXCSTIME:'Timp maxim nava de colonizare',
		FIND:'Cauta',
		TOWNFINDER:'Cauta orase',
	},
	POPSOUNDEG:'exemplu: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
	MSGSHOWCOST:'Costul unitatilor pierdute',
	LASTUPDATE:'1487507969523',
}