RepConvLangArray.fr = {
	INFO:{
		0:'Potusek',
		1:'grepolis@potusek.eu',
	},
	WEBSITE:'Site web',
	AUTHOR:'group.xione@gmail.com, aezeluk, MilleBaffes, Steros, Nico-DiAngelo, Sky-Lop, ThunderLiight, Orience, galoup95, rapha1978',
	BTNCONV:'Convertir',
	BTNGENER:'Générer',
	BTNSRC:'Source',
	BTNVIEW:'Aperçu',
	BTNSAVE:'Sauvegarder',
	BTNMARKS:'Marqué comme lu',
	BTNMARKA:'Marqué tout comme lu',
	MSGTITLE:'Convertir le rapport',
	MSGQUEST:'Que souhaitez vous publier?',
	MSGALL:'tout',
	MSGBBCODE:'Après la publication du rapport, vous pouvez le placer dans les forums en utilisant le BBCode.',
	MSGRESOURCE:'piller',
	MSGUNITS:'Unités',
	MSGBUILD:'Batiments',
	MSGUSC:'Pièces d\'argent utilisées',
	MSGRAW:'Matières première',
	SUPPORT:'soutien',
	SPY:'Espionnage',
	CONQUER:'Conquis',
	LOSSES:'pertes',
	HIDDEN:'caché',
	NOTUNIT:'[i]Rien[/i]',
	TOWN:'[i]Ville:[/i] ',
	PLAYER:'[i]Joueur:[/i] ',
	ALLY:'[i]Alliance:[/i] ',
	CAST:'cast:',
	ONTOWER:'Dans la ville:',
	MSGHIDAD:'Villes masquées',
	MSGFORUM:'Le rapport sera publié',
	BBALLY:'Forum d\'alliance / dans le message',
	BBFORUM:'Forum externe',
	ERRGETSRC:'Une erreur s\'est produite S\'il vous plaît, générer la source et envoyer une pièce jointe à potusek@westtax.info',
	ICOCLOSE:'Fermer',
	ICOHELP:'À propos du convertisseur',
	MSGPREVIEW:'<b>Aperçu rapport</b>',
	HELPTAB1:'A propos',
	HELPTAB2:'Comment ça marche',
	HELPTAB3:'Changements',
	HELPTAB4:'Paramètres',
	HLPVERSION:'Version',
	HLPFIXED:'Corriger',
	HLPADDED:'Ajouter',
	MSGHUMAN:{
		OK:'L\'information a été sauvegardée',
		ERREUR:'Une erreur s\'est produite lors de l\'écriture',
		ERROR:{
		},
		YOUTUBEERROR:'Lien incorrecte ou non autorisé à jouer en dehors du Youtube',
	},
	STATSPOINT:'Points',
	STATSRANK:'Rang',
	LABELS:{
		attack:{
			ATTACKER:'Attaquant',
			DEFENDER:'Défenseur',
			MSGHIDAT:'attaquant',
			MSGHIDDE:'défenseur',
			MSGATTUNIT:'Armée attaquante',
			MSGDEFUNIT:'Armée défensive',
		},
		support:{
			ATTACKER:'Soutenir',
			DEFENDER:'Soutenu',
			MSGHIDAT:'soutenir',
			MSGHIDDE:'soutenu',
			MSGATTUNIT:'Armée de support',
			MSGDEFUNIT:'Armée défensive',
		},
		espionage:{
			ATTACKER:'Espion',
			DEFENDER:'Espionné',
			MSGHIDAT:'espion',
			MSGHIDDE:'espionné',
			MSGATTUNIT:'',
			MSGDEFUNIT:'',
		},
	},
	MSGDETAIL:'les détails des commandes',
	MSGRETURN:'(retour)',
	MSGCLAIM:'réserve la ville',
	MSGCLAIMPPUP:'Générer réservation',
	MSGGENBBCODE:'Générer la liste de BBCode',
	MSGDEFSITE:'Vaincu...',
	MSGLOSSITE:'Pertes...',
	MSGASATT:'... en tant qu\'attaquant',
	MSGASDEF:'... en tant que défenseur',
	MSGDIFF1:'ne pas afficher les différences',
	MSGDIFF2:'afficher les différences',
	MSGDIFF3:'afficher seulement les différences',
	BBCODELIMIT:'Compte tenu du montant limité de texte dans un poste, dans le cas d\'une longue liste, les données ont été divisé en groupes; Chaque groupe sera collé comme une entrée séparée',
	CHKPOWERNAME:'Afficher le temps restant avant la possibilité d\'utiliser le sort',
	CHKNIGHTNAME:'Assombrir la ville en bonus de nuit.',
	CHKFORUMTABS:'Remplacer les barres de défilement sur le forum pour le multi ligne',
	BTNRESERVE:'Réservation',
	LNKRESERVE:'Réservations',
	LBLGETRESER:'Obtenir des données ...',
	BTNCHECK:'Vérification des réserves',
	CHKCMDIMG:'Afficher les icones de destinations des déplacements',
	STATSLINK:'Source des statistiques :',
	BTNSUPPLAYERS:'Liste des joueurs',
	CHKUNITSCOST:'Le rapport montre le coût des unités perdues',
	CHKOCEANNUMBER:'Afficher le numéro des mers',
	MSGRTLBL:'Information de révolte',
	MSGRTSHOW:'Ajouter des informations sur la révolte en cours',
	MSGRTONLINE:'Allez-vous être en ligne lors de la révolte rouge?',
	MSGRTYES:'Oui',
	MSGRTNO:'Non',
	MSGRTGOD:'Dieu',
	MSGRTCSTIME:'CS',
	MSGRTONL:'en ligne ?',
	MSGRTERR:'Vous êtes dans une mauvaise ville <br/> Pour créer des informations de révolte, s\'il vous plaît allez à la ville en révolte :',
	BBTEXT:'Version texte',
	BBHTML:'Version tableau',
	MSG413ERR:'<h3>Le rapport généré est trop grand.</h3><p>Utilisez l\'option disponible pour réduire et publier le rapport sans problèmes.</p>',
	CHKREPORTFORMAT:'Générer les rapports à l\'aide de tableaux',
	WALLNOTSAVED:'Les remparts ne sont pas enregistrés',
	WALLSAVED:'Les remparts sont enregistrés',
	POPSELRECRUNIT:'cliquez, pour sélectionner l\'unité de production par défaut',
	POPRECRUNITTRADE:'cliquez, pour remplir les ressources nécessaires pour l\'unité sélectionnée',
	POPINSERTLASTREPORT:'Collez le dernier rapport converti',
	MSGCOPYREPORT:'Le rapport a été enregistré. Cliquez sur [paste_icon] pour le coller',
	POPDISABLEALARM:'désactiver l\'alarme',
	SOUNDSETTINGS:'Réglages son',
	CHKSOUNDMUTE:'Muet',
	SOUNDVOLUME:'Volume',
	SOUNDURL:'URL du fichier son',
	CHKSOUNDLOOP:'boucle',
	POPSOUNDLOOP:'lire en boucle',
	POPSOUNDMUTE:'Couper le son',
	POPSOUNDPLAY:'Lire avec les paramètres actuels',
	POPSOUNDSTOP:'Arreter la lecture',
	POPSOUNDURL:'Chemin (lien) vers le fichier audio',
	STATS:{
		PLAYER:'Statistiques joueur',
		ALLY:'Statistiques alliance',
		TOWN:'Statistiques ville',
		CHKINACTIVE:'Montrer les joueurs inactifs',
		INACTIVE:'Inactif',
		INACTIVEDESC:{
		},
	},
	ABH:{
		WND:{
			WINDOWTITLE:'Aide construction d\'armée',
			UNITFRAME:'Choisissez le type d\'unité',
			DESCRIPTION1:'Dans cette ville, vous avez [population] population libre',
			DESCRIPTION2:'Qui est suffisant pour construire [max_units]',
			DESCRIPTION3:'Vous [yesno] [research] recherché.',
			DESCRIPTION4:'File d\'attente maximale de [max_queue] unités',
			TARGET:'Choisissez le nombre d\'unités à produire',
			PACKAGE:'Nombre de ressources par envoi (en unités)',
			BTNSAVE:'Enregistrer les paramètres',
			TOOLTIPOK:'Cliquez pour sélectionner l\'unité par défaut pour lequel vous enverrez des ressources',
			TOOLTIPNOTOK:'Le type d\'unité n\'a pas été recherché',
			HASRESEARCH:'avez',
			NORESEARCH:'n\'avez pas',
			SETTINGSAVED:'Les réglages pour [city] ont été enregistrés',
		},
		RESWND:{
			RESLEFT:'Ressources restantes à envoyées',
			IMGTOOLTIP:'Cliquez, pour ajouter les ressources',
		},
	},
	NEWVERSION:{
		AVAILABLE:'Nouvelle version disponible',
		INSTALL:'Installer',
		REMINDER:'Me rappeler plus tard',
		REQRELOAD:'Nécessite le raffraîchissement du site',
		RELOAD:'Raffraîchir',
	},
	LANGS:{
		LANG:'Traduction de la langue',
		SEND:'Envoyer pour publication',
		SAVE:'Sauver et tester',
		RESET:'Restaurer le langage par défaut',
		REMOVE:'Supprimer votre traduction?',
	},
	HELPTAB5:'Traduction',
	BTNSIMUL:'Simulateur',
	EMOTS:{
		LABEL:'Do you want more emoticon?',
		MESS:'collez le lien vers les émoticons, chaque fois sur une nouvelle ligne',
	},
	COMMAND:{
		ALL:'tout',
		INCOMING:'entrant',
		OUTGOING:'sortant',
		FORTOWN:'ville:',
	},
	MOBILEVERSION:'Version mobile',
	AO:{
		TITLE:'Aperçu académie',
	},
	CHKOLDTRADE:'Use old trade layout',
	TSL:{
		WND:{
			TOOLTIP:'Voir les villes triées',
			WINDOWTITLE:'Liste triées des villes',
		},
	},
	WALL:{
		WANTDELETECURRENT:'Voulez vous effacer les données actuelles des remparts?',
		DELETECURRENT:'Effacer les données actuelles',
		LISTSAVED:'Sauvegarder sur le mur le jour',
	},
	RADAR:{
		ALL:'Toutes les villes',
		BTNSAVEDEFAULT:'Sauvegarder les valeurs par défaut',
		TOWNPOINTS:'Points minimum',
		TOWNRESERVED:'Réservation',
		TOWNOWNER:'Propriétaire',
		TOWNNAME:'Ville',
		BTNFIND:'Recherche',
		MAXCSTIME:'Temps maximum en BC',
		FIND:'Recherche',
		TOWNFINDER:'Rechercher villes',
	},
	BBIMG:'image seule',
	MSGSHOWCOST:'Coût des unités perdues',
	LASTUPDATE:'1488490547946',
	POPSOUNDEG:'exemple: https://www.youtube.com/watch?v=v2AC41dglnM, https://youtu.be/v2AC41dglnM, http://www.freesfx.co.uk/rx2/mp3s/10/11532_1406234695.mp3',
}